### ISSUE TITLE
Could not find or load main class

### ISSUE THREAD

**Issue by karlmuscat** [bmuschko/gradle-docker-plugin#473] opened 2017-10-04 02:34 UTC
Hi.

Having issues with creating a basic Docker image using Spring Boot 2.0.0.M3 and gradle-docker-plugin 3.2.0. Everything builds great but upon running the container, it seems like the main class is not being found. The container exits immediately with an error: `'Error: Could not find or load main class ...'`

Attached a sample build.gradle for reference.
[sample.txt](https://github.com/bmuschko/gradle-docker-plugin/files/1354423/sample.txt)

Everything works as it should with Spring 1.5.7.RELEASE and plugin 3.2.0 (or 3.0.11). Upgrading to Spring Boot 2.0.0.M4 is not possible as it generates other issues already reported here [https://github.com/bmuschko/gradle-docker-plugin/issues/467](https://github.com/bmuschko/gradle-docker-plugin/issues/467)

Any ideas?

**Comment by cdancy** [comment] 2017-10-04 16:55
I don't use Spring so can't say exactly what the issue could be but can you get things going without using this plugin and so successfully? Just trying to understand where the bottleneck is. It seems the image is created successfully but starting the container fails?

**Comment by cdancy** [comment] 2017-10-04 20:24
@orzeh any thoughts here? I believe you use spring and may be able to provide more insight.

**Comment by orzeh** [comment] 2017-10-04 21:01
@karlmuscat I can reproduce your issue. It appears because in the docker image there is no JAR with application sources. That being said I don't understand why you use `application` plugin for SpringBoot app? IMO it doesn't make sense and it's the source of problems. Even if the JAR would eventually be in the docker image it would be Spring Boot executable JAR with all dependencies inside it (those dependencies are already in lib folder in the image) and main class located in `BOOT-INF/classes` so the error remains.

**Comment by karlmuscat** [comment] 2017-10-05 10:19
@orzeh I might be missing something here, but I'm using the `application` plugin because it's documented [here](https://github.com/bmuschko/gradle-docker-plugin#usage-examples-1) and without it, the `docker-java-application` tasks (specifically the `dockerBuildImage`) won't be available. (Warning: gradle noob writing)

With both the `application` and `org.springframework.boot` plugins enabled, 2 distributions are generated. This is expected as per Spring's documentation. The `application` one is broken because of what you explained above. The Spring boot one works fine. The problem is that the docker task is picking up the `application` one instead of the Spring boot .tar. 

From the `gradle-docker-plugin` documentation, I can't see a way how to specify the distribution to add, unless I use the `docker-remote-api`, which I want to avoid. What are my options?

**Comment by orzeh** [comment] 2017-10-05 10:31
@karlmuscat AFAIK when you use Spring Boot the best option is to use the `docker-remote-api` plugin and write required tasks by hand. You can also consider some optimizations which are described in my sample repo: https://github.com/orzeh/spring-boot-gradle-docker-sample

**Comment by wwadge** [comment] 2017-10-07 16:32
I got around this by defining this for all projects: 
mainClassName = 'org.springframework.boot.loader.JarLauncher'

**Comment by karlmuscat** [comment] 2017-10-11 08:43
Made it to work by disabling most of the `application` plugin tasks as they are replicated by the Spring Boot plugin. Is it possible that the `docker-gradle-plugin` does not force us to use the `application` plugin but rather picks up the plugin selected by the user?

**Comment by cdancy** [comment] 2017-10-11 13:07
@karlmuscat we are not doing anything special WRT plugins or specifically the application plugin if that's what you're asking.

**Comment by karlmuscat** [comment] 2017-10-11 15:35
@cdancy does the plugin work without including the `application` plugin?

**Comment by cdancy** [comment] 2017-10-11 16:28
I would assume so as I can't see how that would interact with anything we are doing. Have you given things a go? Maybe need to split some of the logic up into separate scripts (shouldn't have to of course)?

**Comment by wwadge** [comment] 2017-10-11 16:37
I think @karlmuscat is referring to: https://github.com/bmuschko/gradle-docker-plugin/blob/f42e16ab4ffeaa16fe59f5ca0a33e28ad9d04fe0/src/main/groovy/com/bmuschko/gradle/docker/DockerJavaApplicationPlugin.groovy#L46

The thing is that spring boot provides an alternate option to using application plugin, for example mainClassName does not need to be specified since the spring boot plugin will search for a main class.

**Comment by cdancy** [comment] 2017-10-11 19:18
aaahhhh ... gotcha. Yeah there may be some ... quirks ... but that's really the case with any plugin and is more/less a direct side-effect of the dynamic nature of groovy/gradle. @orzeh has generally fielded these questions as he uses spring as well. Enough folks ask about similar spring questions so by all means if a "good enough" solution is found please add a snippet to our wiki to help others in the community out.

**Comment by cdancy** [comment] 2018-03-08 20:23
Upgrading to version `3.2.5` of this plugin solves similar spring-boot issues. Closing this for now.

**Closed by cdancy** 2018-03-08 20:23 UTC
Labels: question
