### ISSUE TITLE
build gradle-docker-plugin failed 

### ISSUE THREAD

**Issue by ousema2003** [bmuschko/gradle-docker-plugin#350] opened 2017-02-24 19:13 UTC
i downloaded gradle-docker-plugin-master and get error when try to build project with gradle command 

error trace 

FAILURE: Build failed with an exception.

* Where:
Script '/root/gradle-docker-plugin-master/gradle/release.gradle' line: 13

* What went wrong:
A problem occurred evaluating script.
> repository not found: /root/gradle-docker-plugin-master

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cdancy** [comment] 2017-02-24 19:24
@ousema2003 what exactly are you trying to do? I was able to do the below successfully:

```
git clone https://github.com/bmuschko/gradle-docker-plugin.git
cd gradle-docker-plugin
./gradle clean build
```

**Comment by ousema2003** [comment] 2017-02-24 22:53
applied steps above but get error as below  : 
:integrationTest

com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoaderIntegrationTest > Can create class of type Volume FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at DockerThreadContextClassLoaderIntegrationTest.groovy:52
        Caused by: org.gradle.api.artifacts.ResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
            Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:                                      47
                    Caused by: org.gradle.api.resources.ResourceException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                        Caused by: org.gradle.internal.resource.transport.http.HttpRequestException at DockerThreadContextClassLoaderIntegrat                                      ionTest.groovy:47
                            Caused by: org.gradle.internal.impldep.org.apache.http.conn.ConnectTimeoutException at DockerThreadContextClassLo                                      aderIntegrationTest.groovy:47
                                Caused by: java.net.ConnectException at DockerThreadContextClassLoaderIntegrationTest.groovy:47

com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoaderIntegrationTest > Can create class of type Volumes FAILED
    org.spockframework.runtime.UnallowedExceptionThrownError at DockerThreadContextClassLoaderIntegrationTest.groovy:68
        Caused by: org.gradle.api.artifacts.ResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:61
            Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:                                      47
                    Caused by: org.gradle.api.resources.ResourceException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                        Caused by: org.gradle.internal.resource.transport.http.HttpRequestException at DockerThreadContextClassLoaderIntegrat                                      ionTest.groovy:47
                            Caused by: org.gradle.internal.impldep.org.apache.http.conn.ConnectTimeoutException at DockerThreadContextClassLo                                      aderIntegrationTest.groovy:47
                                Caused by: java.net.ConnectException at DockerThreadContextClassLoaderIntegrationTest.groovy:47

com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoaderIntegrationTest > Can create class of type InternetProtocol with scheme TCP FA                                      ILED
    org.spockframework.runtime.UnallowedExceptionThrownError at DockerThreadContextClassLoaderIntegrationTest.groovy:83
        Caused by: org.gradle.api.artifacts.ResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:78
            Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DockerThreadContextClassLoaderIntegrationTest.groovy:                                      47
                    Caused by: org.gradle.api.resources.ResourceException at DockerThreadContextClassLoaderIntegrationTest.groovy:47
                        Caused by: org.gradle.internal.resource.transport.http.HttpRequestException at DockerThreadContextClassLoaderIntegrat                                      ionTest.groovy:47
                            Caused by: org.gradle.internal.impldep.org.apache.http.conn.ConnectTimeoutException at DockerThreadContextClassLo                                      aderIntegrationTest.groovy:47
                                Caused by: java.net.ConnectException at DockerThreadContextClassLoaderIntegrationTest.groovy:47

**Comment by ousema2003** [comment] 2017-02-25 08:41
how to generate gradle-docker-plugin  jar files ?

**Comment by cdancy** [comment] 2017-02-25 13:52
@ousema2003 not sure exactly what you're trying to invoke but I can't reproduce that stacktrace locally even with docker stopped. Not sure how familiar you are with gradle but you can always invoke the `assemble` command to bypass any testing: `./gradlew clean assemble`?

What is your purpose for needing to generate jars locally? Is this for a PullRequest? We already publish our releases to jcenter/maven so they can easily be resolved via gradle maven.

**Comment by ousema2003** [comment] 2017-02-25 13:58
my aim is to use gradle docker plugin to manager docker images/containers remotly through gradle .

you can provide an example for that ?

**Comment by cdancy** [comment] 2017-02-25 13:59
@ousema2003 have you read this projects main page at all? It says exactly how to do so. We also have loads of test files which in themselves are examples of how to do various things.

**Closed by cdancy** 2017-02-25 13:59 UTC
Labels: question

**Comment by ousema2003** [comment] 2017-02-25 14:01
in term of docker engine configuration (host/ogin/passw/port) from gradle client ?

**Comment by cdancy** [comment] 2017-02-25 14:03
@ousema2003 think you need to look into gradle a bit more and get a firm understanding of how it works before trying to play with this plugin. 

I would also recommend reading up on docker and how it works so that you're not so confused.
