### ISSUE TITLE
Document plugin application while in multi-project builds

### ISSUE THREAD

**Issue by MarkRx** [bmuschko/gradle-docker-plugin#1201] opened 2023-11-03 14:57 UTC
When [registering a shared service](https://github.com/bmuschko/gradle-docker-plugin/blob/7f2f5d98556213db1db0db3403f3b096587ae189/src/main/java/com/bmuschko/gradle/docker/DockerRemoteApiPlugin.java#L33) the registration should be done in the root project or else class loading issues can occur in certain situations in multi-project builds or with script plugins. This can be effectively accomplished by instructing users to apply the docker plugin to the root project before applying it in any child projects.

The class loader exception will look like the following:

```
Caused by: java.lang.IllegalArgumentException: Cannot set the value of task 'xxx' property 'dockerClientService' of type com.bmuschko.gradle.docker.internal.services.DockerClientService using a provider of type com.bmuschko.gradle.docker.internal.services.DockerClientService.
        at org.gradle.api.internal.provider.AbstractMinimalProvider.asSupplier(AbstractMinimalProvider.java:158)
        at org.gradle.api.internal.provider.DefaultProperty.set(DefaultProperty.java:100)
        at com.bmuschko.gradle.docker.DockerRemoteApiPlugin$2.execute(DockerRemoteApiPlugin.java:47)
        at com.bmuschko.gradle.docker.DockerRemoteApiPlugin$2.execute(DockerRemoteApiPlugin.java:44)
```

**Comment by bmuschko** [comment] 2023-11-03 15:04
The issue you reported is a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/1182. It's currently a limitation in Gradle core. I believe they have an issue open for it.

**Comment by bmuschko** [comment] 2023-11-07 17:33
Were you able to set up your project?

**Comment by bmuschko** [comment] 2023-11-07 17:52
I created a note to the documentation with https://github.com/bmuschko/gradle-docker-plugin/pull/1202.

**Closed** 2023-11-13 19:26 UTC
Labels: question

**Comment by big-andy-coates** [comment] 2024-01-09 18:34
Said note helped me :)
