### ISSUE TITLE
Plugin cannot be applied to more than one project

### ISSUE THREAD

**Issue by Kantis** [bmuschko/gradle-docker-plugin#1152] opened 2023-01-17 10:31 UTC
### Expected Behavior
Given a multi-module project with the structure:
```
:shared
:client-application
:server-application
```

Applying the `com.bmuschko.docker-spring-boot-application` plugin in both the client-application and server-application (which are both Spring Boot apps) should work and register relevant tasks for each.

### Current Behavior
Adding the plugin to a second module throws:
```
java.lang.IllegalArgumentException: Cannot set the value of task ':server-application:dockerBuildImage' property 'dockerClientService' of type com.bmuschko.gradle.docker.internal.services.DockerClientService using a provider of type com.bmuschko.gradle.docker.internal.services.DockerClientService.
```

### Context
I want to generate multiple docker images within the same gradle proejct

### Steps to Reproduce (for bugs)

)

Described above but can try to create a functional test if desired.

### Your Environment
MacOS M1, JDK 17, Gradle 7.6

**Comment by bmuschko** [comment] 2023-01-20 23:14
I am pretty sure this is a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/1123.

**Closed** 2023-01-20 23:15 UTC
Labels: duplicate
