### ISSUE TITLE
Cant use plugin in precompiled script plugins

### ISSUE THREAD

**Issue by vrapalis** [bmuschko/gradle-docker-plugin#1018] opened 2021-06-09 07:15 UTC
Can't use the plugin in precompiled script plugin

### Expected Behavior

Ability to use and customize the docker plugin inside precompiled script plugin
used this instructions => [https://bmuschko.github.io/gradle-docker-plugin/#applying_the_plugin_from_a_script_plugin](script plugin) but also tried => [buildscriptsyntax](https://bmuschko.github.io/gradle-docker-plugin/#applying_the_plugin_using_the_buildscript_syntax) and [1.5.2. Applying the Plugin Using the Plugin DSL](dsl)

### Current Behavior

Precompiled script plugin

buildscript {
    repositories {
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:6.7.0'
    }
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

error => Could not get unknown property 'com' for root project

### Steps to Reproduce (for bugs)

Creatre precompiled script plugin and use in this plugin docker plugin

### Your Environment

gradle => Gradle 7.0.2
Groovy =>       3.0.7
java => openjdk version "16.0.1" 2021-04-20

**Comment by bmuschko** [comment] 2021-06-09 13:14
Can you please provide a GitHub repository that reproduces the issue (including the Wrapper)?

BTW: The `plugins` DSL does not work in general in a script plugin. That's simply a Gradle limitation.

**Comment by vrapalis** [comment] 2021-06-09 15:05
> Can you please provide a GitHub repository that reproduces the issue (including the Wrapper)?
> 
> BTW: The `plugins` DSL does not work in general in a script plugin. That's simply a Gradle limitation.

Thx, you can clone this project https://github.com/enterprise-it-solutions/monorepository
and then import /backend/apps/entryou as gradle project, in build file of gradle i use plugin docker created by me, this project (Entryou) is using includeBuilds, plugins project will be imported in idea aswell, then you can look at plugins/docker precompailed plugin. Sorry for my english :)

**Comment by bmuschko** [comment] 2021-06-09 15:19
Can you condense this code a bit? There's a lot of code in there that's not relevant to the problem. Also, if you create your own plugin that uses my plugin then the published plugin (yours) needs to declare my plugin in its published POM. Is that the case?

**Comment by vrapalis** [comment] 2021-06-10 16:37
> Can you condense this code a bit? There's a lot of code in there that's not relevant to the problem. Also, if you create your own plugin that uses my plugin then the published plugin (yours) needs to declare my plugin in its published POM as a runtime dependency. Is that the case? If not, then it won't be on the classpath.
> 
> Also, your use case is vastly different from what you described in your ticket initially.

I have created another short project [Project](https://github.com/vrapalis/docker-plugin-example). How can i use your plugin inside precompiled script plugin, and then consum my plugin?

**Comment by bmuschko** [comment] 2021-06-10 18:57
A couple of comments:

1. Your question isn't really specific to this plugin here. Yes, you are using it but the problem you are trying to solve is not specific to this plugin. I'd ask you to ask the question on the Gradle forum. I don't have the bandwidth to help with general Gradle questions. I won't be able to follow up here. Sorry!
2. Precompiled script are meant to live in `buildSrc` if you don't want to publish the binary of your plugin separately. Maybe you only showed this as example here.
3. To add my plugin to your plugin, you'd need to add a compile or runtime dependency to your plugin. Right now, you are not doing that. This needs to be defined outside of `buildscript`. You are just adding it to the classpath of the script plugin.

**Comment by bmuschko** [comment] 2021-06-14 23:29
Closing this question as the issue is really more of a generic Gradle question.

**Closed by bmuschko** 2021-06-14 23:29 UTC
Labels: question
