### ISSUE TITLE
DockerPushImage - ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected

### ISSUE THREAD

**Issue by pgcortina** [bmuschko/gradle-docker-plugin#515] opened 2018-01-12 01:32 UTC
We are intermittently getting the following exception while trying to push a docker image to the registry (artifactory). Any idea why this could be happening?

`
[15:43:01][Step 4/6] :service:publishDockerImage (3s)
[15:43:01][:service:publishDockerImage] Running in a non-OSGi environment
[15:43:01][:service:publishDockerImage] Pushing image with name 'docker-dev-artifactory.xxx.com/service/service'.
[15:43:01][:service:publishDockerImage] Selected ExecutorServiceProvider implementation [org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
[15:43:04][:service:publishDockerImage] [dockerjava-jaxrs-async-0] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
[15:43:04][:service:publishDockerImage] org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
[15:43:04][:service:publishDockerImage] 	at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:267)
[15:43:04][:service:publishDockerImage] 	at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:226)
[15:43:04][:service:publishDockerImage] 	at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:185)
[15:43:04][:service:publishDockerImage] 	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
[15:43:04][:service:publishDockerImage] 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[15:43:04][:service:publishDockerImage] 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[15:43:04][:service:publishDockerImage] 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[15:43:04][:service:publishDockerImage] 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[15:43:04][:service:publishDockerImage] 	at java.io.FilterInputStream.read(FilterInputStream.java:133)
[15:43:04][:service:publishDockerImage] 	at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:102)
[15:43:04][:service:publishDockerImage] 	at com.github.dockerjava.jaxrs.util.WrappedResponseInputStream.read(WrappedResponseInputStream.java:44)
[15:43:04][:service:publishDockerImage] 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
[15:43:04][:service:publishDockerImage] 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd2(UTF8StreamJsonParser.java:2904)
[15:43:04][:service:publishDockerImage] 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._skipWSOrEnd(UTF8StreamJsonParser.java:2899)
[15:43:04][:service:publishDockerImage] 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:692)
[15:43:04][:service:publishDockerImage] 	at com.github.dockerjava.core.async.JsonStreamProcessor.processResponseStream(JsonStreamProcessor.java:56)
[15:43:04][:service:publishDockerImage] 	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:66)
[15:43:04][:service:publishDockerImage] 	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
[15:43:04][:service:publishDockerImage] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:43:04][:service:publishDockerImage] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[15:43:04][:service:publishDockerImage] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[15:43:04][:service:publishDockerImage] 	at java.lang.Thread.run(Thread.java:748)
`
Using **com.bmuschko:gradle-docker-plugin:3.2.1**

**Comment by orzeh** [comment] 2018-01-15 14:00
@pgcortina can you push any image using Docker CLI?

**Comment by pgcortina** [comment] 2018-01-16 20:24
@orzeh yes, we can, without issues. Interestingly this issue started happening last week in our builds using the Gradle plugin and it has been pretty spotty, hard to reproduce. We are also looking into infrastructure issues on our side, but wanted to raise up the question in case somebody experienced a similar issue.

**Comment by orzeh** [comment] 2018-01-16 20:32
@pgcortina OK. I have a feeling that it's some infrastructure issue. Anyway let us know if you find solution.

**Comment by cdancy** [comment] 2018-01-17 02:19
Curious... what version of our plugin are you using? I know we had an issue with this in the past but it's long since been solved.

**Comment by pgcortina** [comment] 2018-01-17 02:25
We are using com.bmuschko:gradle-docker-plugin:3.2.1

**Comment by cdancy** [comment] 2018-01-17 15:11
Yeah the only thing I can think is maybe you're on an older version of docker?

**Comment by pgcortina** [comment] 2018-01-17 18:24
We are using Docker version 17.05.0-ce, build 89658be

**Comment by cdancy** [comment] 2018-01-17 18:29
Yeah that should be new enough. We're using the latest and greatest at the moment with no issues. If you have a reproducible snippet I can give things a go.

What does your environment look like? Where are you publishing to (e.g. artifactory, dockerhub, custom registry)?

**Comment by pgcortina** [comment] 2018-03-07 01:34
This has not happened again, it was an issue with our own network looks like.

**Comment by orzeh** [comment] 2018-03-07 08:19
@pgcortina thanks for feedback. I'm closing this issue then.

**Closed by orzeh** 2018-03-07 08:19 UTC

**Comment by maitreyak** [comment] 2019-06-11 21:38
@pgcortina @orzeh I was able to reproduce the issue. 
In our case it had nothing to do with the network. The artifact we were pushing already existed in artifactory. 

```org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':artifactoryDeploy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipCachedTaskExecuter.execute(SkipCachedTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ResolveBuildCacheKeyExecuter.execute(ResolveBuildCacheKeyExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
        at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:76)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:784)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:751)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 31 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of chunk coded message body: closing chunk expected
        at org.apache.http.impl.io.ChunkedInputStream.getChunkSize(ChunkedInputStream.java:266)
        at org.apache.http.impl.io.ChunkedInputStream.nextChunk(ChunkedInputStream.java:225)
        at org.apache.http.impl.io.ChunkedInputStream.read(ChunkedInputStream.java:184)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1680)
        at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1659)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1636)
        at org.apache.commons.io.IOUtils.copy(IOUtils.java:1611)
        at org.apache.commons.io.IOUtils.toString(IOUtils.java:668)
        at org.jfrog.build.client.ArtifactoryHttpClient.execute(ArtifactoryHttpClient.java:225)
        at org.jfrog.build.client.ArtifactoryHttpClient.upload(ArtifactoryHttpClient.java:216)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.uploadFile(ArtifactoryBuildInfoClient.java:680)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.doDeployArtifact(ArtifactoryBuildInfoClient.java:367)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:355)
        at org.jfrog.build.extractor.clientConfiguration.client.ArtifactoryBuildInfoClient.deployArtifact(ArtifactoryBuildInfoClient.java:340)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.deployArtifacts(DeployTask.java:262)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.prepareAndDeploy(DeployTask.java:113)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.collectProjectBuildInfo(DeployTask.java:50)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.taskAction(DeployTask.java:44)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)```

**Comment by orzeh** [comment] 2019-06-11 22:31
@maitreyak so this issue might be specific to how Artifactory Image Registry works? Is that correct?

**Comment by cdancy** [comment] 2019-06-12 01:17
@maitreyak what version of Artifactory are you on? Latest and greatest here and we use the plugin extensively for this sort of thing and havent hit this issue.

**Comment by chienkuo** [comment] 2020-11-26 07:18
ok, it may be the docker-java's issues, it can be get the exception by executing InspectContainerCmd with none exists container id.
