### ISSUE TITLE
No 'maintainer' attribute for Spring Boot Application Plugin

### ISSUE THREAD

**Issue by fml2** [bmuschko/gradle-docker-plugin#779] opened 2019-03-28 10:16 UTC
We'd like to create a docker image for a spring boot application. We switched to the spring-boot plugin after having used the Java Application Plugin.

In the Java Application Plugin, it was possible to specify the 'maintainer' attrbute of the docker image to produce:

```
docker {
  javaApplication {
    maintainer = 'maintaner@myorg.com'
  }
}
```

However, when using the Spring Boot Application Plugin, there seems to be no way to specify the maintainer.

How whould one do that?

**Comment by bmuschko** [comment] 2019-03-28 13:08
This property is not available in the Spring Boot application plugin. To be honest I'd like to get rid of it in the Java application plugin as well to align the functionality.

Here's the reason why: The Docker instruction MAINTAINER has been deprecated. You are now supposed to use a LABEL. It's also very easy to add that instruction without the use of a plugin extension. Just add the instruction to the task that builds the Dockerfile.

```
dockerCreateDockerfile {
    label([''maintainer'', 'yourname'])
}
```

**Comment by cdancy** [comment] 2019-03-28 18:02
@bmuschko care to send in a PR? :) It's been gone for quite some time now

**Comment by fml2** [comment] 2019-03-28 19:30
bmuschko, thank you for the tip! I'll try it out. It will surely work. If you wish, you can close the issue now, and we'll reopen it if there are some problems.

**Comment by fml2** [comment] 2019-03-29 08:17
I changed the build script as you advised and can see the 'label' entry in the generated docker file:

`LABEL maintainer="My Org <maintainer@myorg.com>"`

So everything looks like it should here.

The weird thing is that in Harbour, where we push our images, I don't see any value in the column "Author".

**Comment by bmuschko** [comment] 2019-04-02 23:21
I haven't used Harbour but my guess is that they only take into account the MAINTAINER instruction and not a LABEL with the key `maintainer`. Try to see if you find the actual label in the UI. Not sure what the issue is. Also ensure that the Dockerfile actually contains the instruction.

We can have a look at the naming problem in another issue.

**Comment by bmuschko** [comment] 2019-04-16 17:05
Seems like there's no more traction on this issue. Closing this for now.

**Closed by bmuschko** 2019-04-16 17:05 UTC
Labels: question

**Comment by bmuschko** [comment] 2019-05-05 13:11
I decided to expose the property for the plugin with the next release.

**Comment by bmuschko** [comment] 2019-05-11 21:19
This has been released.
