### ISSUE TITLE
Applying multiple tags to created image fails with NullPointerException

### ISSUE THREAD

**Issue by dpr-rec** [bmuschko/gradle-docker-plugin#248] opened 2016-07-19 11:37 UTC
I'm trying to apply multiple tags to an image created with a `DockerCreateImage` task. As the `DockerTagImage` task only supports a single tag, I'm creating tagging tasks on the fly in my gradle build based on the configured tags (basically a comma separated list):

build.gradle:
``` groovy
apply from: "${project.rootDir}/gradle/docker-utils.gradle"
...
task createImage(type: DockerBuildImage) {
  inputDir = file('src/main/docker')
  tag = dockerProps['name']
}

//task tagImage(type: DockerTagImage) {
//  targetImageId { createImage.getImageId() }
//  repository = dockerProps['name']
//  tag = dockerProps['tags'].split(',')[0]
//}
task tagImage << {
  tagDockerImage(createImage.getImageId(), dockerProps['name'], dockerProps['tags'].split(','))
}
tasks.createImage.finalizedBy(tagImage)
```
docker-utils.gradle:
``` groovy
buildscript {
  repositories { mavenCentral() }

  dependencies {
    classpath group: 'com.bmuschko', name: 'gradle-docker-plugin', version: '2.6.8'
  }
}
import com.bmuschko.gradle.docker.tasks.image.DockerTagImage

def tagDockerImage(String aImageId, String aName, String[] aTags) {

  def i = 0
  aTags.each { tagIt ->
    def tagTask = tasks.create(name: "tagDockerImage${i}", type: DockerTagImage) {
      targetImageId { aImageId }
      repository = aName.trim()
      tag = tagIt.trim()
    }

    tagTask.doFirst { logger.info "Tagging image '${imageId}' with tag '${repository}:${tag}'" }

    tagTask.execute()
    i++
  }
}

// Export methods by turning them into closures
ext { tagDockerImage = this.&tagDockerImage }
```

This works fine in a single project build but in a multi-project built I'm getting a `NullPointerException`:

```
Script 'C:\ws\gradle\docker-utils.gradle' line: 23

* What went wrong:
Execution failed for task ':docker-build:tagDockerImage0'.
> Cannot invoke method withClasspath() on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':docker-build:tagDockerImage0'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.execute(AbstractTask.java:305)
        at org.gradle.api.internal.TaskInternal$execute$0.call(Unknown Source)
        at docker_utils_xgqqku9s19rhgyrizdsi68vr$_tagDockerImage_closure2.doCall(C:\ws\AXC_DEFAULT_1\ng\gradle\docker-utils.gradle:26)
        at docker_utils_xgqqku9s19rhgyrizdsi68vr.tagDockerImage(C:\ws\AXC_DEFAULT_1\ng\gradle\docker-utils.gradle:17)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:159)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
        at axcng_docker_build_56wjd78akrg79ut9ugohy4zrb$_run_closure3.doCall(C:\ws\AXC_DEFAULT_1\ng\axcng-docker-build\axcng-docker-build.gradle:27)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:77)
        at org.gradle.api.internal.tasks.TaskMutator$1.execute(TaskMutator.java:73)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NullPointerException: Cannot invoke method withClasspath() on null object
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
        at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:56)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 35 more
```

I just noticed that it works as well, if I put the `tagDockerImage` function directly into the build.gradle file of the docker project, instead of importing it from another gradle file by `apply from`. This is however not the desired solution as I have multiple docker sub-projects in this setup and I don't like to copy & paste this function to each of the projects...

**Comment by orzeh** [comment] 2016-07-19 12:02
Did you apply the plugin to each Gradle sub project?

**Comment by dpr-rec** [comment] 2016-07-19 12:41
To each docker related project, yes

**Comment by orzeh** [comment] 2016-07-19 13:59
I believe this is problem is related to how you use this plugin in your build scripts. 

When this plugin is applied then it internally do this:
````groovy
project.tasks.withType(AbstractDockerRemoteApiTask) {
   group = DEFAULT_TASK_GROUP
   threadContextClassLoader = dockerClassLoader
}
````
According to the stacktrace the problem is in:
````groovy
void runInDockerClassPath(Closure closure) {
   threadContextClassLoader.withClasspath(getClasspath()?.files, createDockerClientConfig(), closure)
}
````
so `threadContextClassLoader` was not set.

You create your `tagDockerImageX` tasks dynamically inside a custom function which is invoked as a `doLast` action of another task. I think these tasks do not exist when above code is executed and that is why you receive NPE during build. However, it is strange that it works if you move `tagDockerImage` to the build file of a project.

Can you provide some test project demonstrating the issue so I can play with it?

**Comment by dpr-rec** [comment] 2016-07-19 14:02
Will try, but may take some time... Thanks for the support, so far.

**Comment by dpr-rec** [comment] 2016-07-19 14:26
Maybe this is somewhat helpful. I changed the `tagDockerImage` function to set the class loader:

``` groovy
def tagDockerImage(String aImageId, String aName, String[] aTags) {

  def i = 0
  ThreadContextClassLoader dockerClassLoader = new DockerThreadContextClassLoader(project.extensions.getByName('docker'))
  aTags.each { tagIt ->
    def tagTask = tasks.create(name: "tagDockerImage${i}", type: DockerTagImage) {
      targetImageId { aImageId }
      repository = aName.trim()
      tag = tagIt.trim()
      threadContextClassLoader = dockerClassLoader
    }

    tagTask.doFirst { logger.info "Tagging image '${imageId}' with tag '${repository}:${tag}'" }

    tagTask.execute()
    i++
  }
}
```

Now I'm getting this error, when running the build:

```
> Could not find matching constructor for: com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader(com.bmuschko.gradle.docker.DockerExtension_Decorated)
```

That is the docker extension is not of type `DockerExtension` but `DockerExtension_Decorateed` when the tasks are created...

**Comment by dpr-rec** [comment] 2016-07-20 14:35
I created an example to reproduce the problem: https://github.com/dpr-rec/gradle-docker-plugin-248

While trying to create this example I boiled the problem down to the dependency to `com.github.jengelman.gradle.plugins:gradle-processes:0.3.0` (https://github.com/johnrengelman/gradle-processes) which is a transitive dependency of `com.github.robfletcher:compass-gradle-plugin:2.0.6` (https://github.com/robfletcher/gradle-compass). Already the presence of this dependency in the gradle file causes this `NullPointerException`. If the dependency is removed, tagging of the docker images works.

If it is not too much effort, maybe you could check what might be causing this problem internally?! That would be highly appreciated, as I currently have not setup anything to debug gradle plugins...

**Comment by orzeh** [comment] 2016-07-20 14:39
Thanks! I wilk take a look

**Comment by orzeh** [comment] 2016-07-20 22:08
OK, after a while I know what is happening, however it is strange. 

I don't know why, but it works when dependencies of __both__ build scripts - main and included via `apply from:` __are the same__. If they are different, NPE is thrown because - as I supposed - your dynamically created tasks do not appear in `project.tasks.withType(AbstractDockerRemoteApiTask)` collection.
I've made a [PR](https://github.com/dpr-rec/gradle-docker-plugin-248/pull/1) demonstrating a fix for your sample project - please take a look on it.

I've no idea why Gradle is behaving in a such way, @bmuschko can you help and explain what is actually going on?

**Comment by dpr-rec** [comment] 2016-07-21 08:37
I getting even weirder.

Your "fix" was not working for me until I changed the **order** of the buildscript dependencies in the applied gradle file to match the order in the root build.gradle. That is:

working:
```groovy
dependencies {
  classpath 'com.github.jengelman.gradle.plugins:gradle-processes:0.3.0'
  classpath group: 'com.bmuschko', name: 'gradle-docker-plugin', version: '2.6.8'
}
```

not working:
```groovy
dependencies {
  classpath group: 'com.bmuschko', name: 'gradle-docker-plugin', version: '2.6.8'
  classpath 'com.github.jengelman.gradle.plugins:gradle-processes:0.3.0'
}
```

Again the `com.github.johnrengelman.processes` is not applied to any of the projects in the example. The problem is already caused by simple adding the respective dependency (in the wrong order).

**Comment by dpr-rec** [comment] 2016-07-21 10:30
Ok, I played around a little bit and this problem doesn't seem to be specifically related to the `com.github.jengelman.gradle.plugins:gradle-processes:0.3.0` plugin, but to the buildscript dependencies in general. In our real-life project we have multiple buildscript dependencies (11 in total). To make the imported gradle file working, I needed to add all of these dependencies to the imported file **in exactly the same order** as in the root build.gradle file.

**Comment by orzeh** [comment] 2016-07-21 11:29
So this is a Gradle issue not `gradle-docker-plugin`.
I don't have enough knowledge about Gradle internals to track it down, so we need some help from Gradle community.

**Comment by dpr-rec** [comment] 2016-07-21 12:03
Actually I'm not sure. `gradle-docker-plugin` is the first of the 11 plugins that has problems like this. That is it may be a Gradle issue and/or an issue with the way `gradle-docker-plugin` uses Gradle.

But I'm not that much into the Gradle internals as well to be able to make a qualified judgement on this...

**Comment by cdancy** [comment] 2016-07-25 01:11
@dpr-rec with gradle 3.0.0 the plugin model is supposed to be more isolated thereby not allowing the clobbering one typically sees with 2.x. There is an ISSUE/documentation on this work somewhere but I'm failing to find it at the moment.

I've run into similar issues and indeed re-ordering the classpath, however unfortunate, does cause the problem to "go away".

**Comment by dpr-rec** [comment] 2016-07-25 08:58
@cdancy  thanks for the update. Hopefully updating to Gradle 3.0.0 will not be much of an effort, once it is released...

**Comment by cdancy** [comment] 2016-07-25 12:53
@dpr-rec I'm going to close this issue for now as there is a work around. This is more due to gradles handling of plugin dependencies (which we try our best to get around) than I think anything else.

**Closed by cdancy** 2016-07-25 12:53 UTC
Labels: help wanted

**Comment by MarkRx** [comment] 2016-08-03 16:15
I am also hitting this issue. Is there no other way to resolve it? The workaround of duplicating the buildscript dependency classpath ordering isn't pretty when having a more complicated build.

**Comment by MarkRx** [comment] 2016-08-03 17:20
Per Peters post @ https://discuss.gradle.org/t/how-do-i-apply-a-plugin-to-a-project-from-a-shared-applied-gradle-file/7508/2 it can be solved by applying the plugin in the plugin buildscript like this:

`apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin`

**Comment by dpr-rec** [comment] 2016-08-04 11:15
@MarkRx this problem seems to be related but slightly different as I'm not applying the plugin from the shared gradle file but am using classes from the plugin to implement a custom task. Applying the plugin by using `apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin` instead of `apply plugin: 'com.bmuschko.docker-remote-api'` in the project's gradle file did not solve the problem.

**Comment by kentoj** [comment] 2017-07-08 23:31
There is a supported, simpler way of doing this now. See the example I posted to this repository's wiki [here](https://github.com/bmuschko/gradle-docker-plugin/wiki/examples#building-a-docker-image-from-a-dockerfile-with-multiple-tags).

**Comment by cdancy** [comment] 2017-07-09 01:25
Thanks @kentoj for starting the examples page!

**Comment by kentoj** [comment] 2017-07-09 12:14
It was my pleasure. I am likely to use it myself quite a bit. I like to keep the documentation as close to the source as practical.

**Comment by dpr-rec** [comment] 2017-07-11 07:05
@kentoj Thanks for the update. What version of gradle-docker-plugin is needed the tag images this way?

**Comment by orzeh** [comment] 2017-07-11 07:25
@dpr-rec it was introduced in `3.0.8` (see [RELEASE_NOTES](https://github.com/bmuschko/gradle-docker-plugin/blob/master/RELEASE_NOTES.md#version-308-june-16-2017))

**Comment by fhanik** [comment] 2017-08-09 17:56
we fixed our build by

replacing 

    apply plugin: 'com.bmuschko.docker-remote-api'
with

    apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

per documentation at https://github.com/bmuschko/gradle-docker-plugin

and that solved the issue of 

    "at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)"

**Comment by cdancy** [comment] 2017-08-09 17:59
@fhanik I assume you were using the plugin in a file that was NOT the main build file?
