### ISSUE TITLE
Use different CI solution

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#345] opened 2017-02-14 15:41 UTC
[SnapCI is going to shut down](https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/) in August 2017. Find a different, free CI product optimally with support for modeling pipelines.

**Comment by cdancy** [comment] 2017-02-14 16:17
Thanks for passing this along @bmuschko.

@orzeh any thoughts or opinions one way or the other? I say lets go with travis as there is built in docker support and it's stupid-simple to use.[ I use it in my own projects](https://github.com/cdancy/bitbucket-rest/blob/master/.travis.yml) and find it to be great.

**Comment by bmuschko** [comment] 2017-02-14 16:25
The problem you will have with Travis is the fact that you'll always have to release from your local machine as there's no manual step you can invoke for a release as part of a pipeline.

**Comment by cdancy** [comment] 2017-02-14 17:11
@bmuschko that might be Ok as that's the model I've adapted for my own projects and works well enough. 

But taking things further: maybe we move to a `SNAPSHOT` model where every successful merge is a new SNAPSHOT published. Only when we are ready to release do we change the version property from X.X.X-SNAPSHOT to X.X.X. Then directly after release we add the SNAPSHOT back for the next development iteration.

**Comment by bmuschko** [comment] 2017-02-14 17:11
It's up to you. I am personally not a fan of SNAPSHOT builds.

**Comment by cdancy** [comment] 2017-02-14 17:15
@bmuschko yeah I don't either to be honest but I know of a few folks that have asked for them. I'll mull it over a bit more and see if anything jumps out.

**Comment by orzeh** [comment] 2017-02-15 08:51
@bmuschko @cdancy I don't have any experience with Travis but it looks :ok_hand: and supports Docker.

IMO we should enable `SNAPSHOT` model as it allows folks to test things immediately and gather feedback. Maybe we can use [Gradle Git](https://github.com/ajoberstar/gradle-git) plugin to  infer project version and release (manually). I use it in many personal projects and it works well.

**Comment by bmuschko** [comment] 2017-02-15 12:38
> ...and supports Docker.

What exactly does it mean that TravisCI supports Docker? Does it mean that the builds run in Docker containers or that it offers a Docker registry? I personally do not care too much about the fact that a CI provider runs on Docker. To me as an end user that's an implementation detail. I just want it to work. :-)

> IMO we should enable SNAPSHOT model as it allows folks to test things immediately and gather feedback.

Please keep in mind that the decision will have an impact on the automated release process. Usually, it's not trivial to ensure that this works properly. From my perspective there's no point in using SNAPSHOT for testing purposes. If there's a new feature for the plugin then simply release it with a new final version. Boom, done! Given that the release process at the moment is non-event (you just press a button really) it don't see the need for SNAPSHOT. In fact I often times released a new version of the plugin after merging a single PR that maybe just added a new property to a task.

**Comment by orzeh** [comment] 2017-02-15 13:06
> What exactly does it mean that TravisCI supports Docker?

According to the [docs](https://docs.travis-ci.com/user/docker/) we can have Docker engine installed on testing machine. In our case it can simply running functional tests.

The build itself [can be run in a container](https://docs.travis-ci.com/user/ci-environment/), but as you said we should not care about it.

> If there's a new feature for the plugin then simply release it with a new final version

This is the best option.

**Comment by bmuschko** [comment] 2017-02-15 13:07
> This is the best option.

We already have that in place. That's why I don't necessarily want to go for a SNAPSHOT solution as it will definitely make the release process more complex.

**Comment by cdancy** [comment] 2017-02-15 14:24
@bmuschko @orzeh two different things we are talking about there. Lets shelve the SNAPSHOT conversation to some later date and focus on a CI service. 

As has been noted already: travis I believe runs inside a container (which shouldn't matter to us one way or the other) but also provides docker (if requested) allowing us to run functional tests and NOT have to rely on the user to do so. Too many times have users assumed, and rightly so IMO, that submitting a PR would also trigger running all applicable tests. We need to nip this in the butt already and have a full end-to-end CI solution in place. Travis can provide this for us and it's what I see most projects using nowadays. Stupid-simple, gets out of your way, and just works as expected.

**Comment by bmuschko** [comment] 2017-02-22 00:02
I tried out GitLab over the weekend which seems to work nicely. Do you have permissions to display  https://gitlab.com/bmuschko/gradle-docker-plugin/pipelines? I am a little unsure about the permissions. GitLab supports CI pipelines. Only bummer is that it creates a new container for every step of the pipeline which costs additional time. Check it out and let me know what you think.

**Comment by orzeh** [comment] 2017-02-22 11:34
@bmuschko I use GitLab at work and its CI works fine. However, running functional tests here will be much harder than in Travis.

I don't have permissions to see https://gitlab.com/bmuschko/gradle-docker-plugin/pipelines - returns `404`.

**Comment by bmuschko** [comment] 2017-02-22 13:38
@orzeh OK, thanks for the info. Do you know how to configure the GitLab project to render the pipeline for everyone. I already checked the option "public pipeline".

**Comment by orzeh** [comment] 2017-02-22 13:47
@bmuschko unfortunately no. We use private/internal projects only.

**Comment by cdancy** [comment] 2017-02-22 14:11
@bmuschko same issue here. I can log in easily enough with github credentials but can't do much else at the moment. Poking around...

But just to re-iterate what @orzeh said: having a CI service which can execute docker so that we can run functionalTests I think is a must moving forward. Every PR that comes through I've been manually running that branch locally to ensure all functionalTests pass: shouldn't have to do that.

**Comment by bmuschko** [comment] 2017-05-05 12:46
Did you guys make some progress on setting up a new CI solution? I am assuming you'll soon not be able to build and release anymore.

**Comment by cdancy** [comment] 2017-05-05 12:51
@bmuschko not yet. I'll put it on my local backlog to knock it out within the next week or so. My personal opinion would be to use travis-ci, and while it does not provide what other CI services do, I think with the appropriate documentation in place, and how to release, it should not be an issue. 

Thinking we can share the release credentials amongst ourselves over email or something like that.

**Comment by bmuschko** [comment] 2017-05-05 13:12
I am not super excited to share my Bintray GPG_PASSPHRASE to be honest. I'd much rather like to see a solution that can perform the release with a click of a button.

**Comment by cdancy** [comment] 2017-05-05 13:14
@bmuschko we could use a service account with username/password to publish artifacts: doesn't need to be your personal GPG passphrase.

**Comment by bmuschko** [comment] 2017-05-05 13:19
@cdancy Sure, if you can make that happen with the [already existing setup in Bintray](https://bintray.com/bmuschko/gradle-plugins/com.bmuschko%3Agradle-docker-plugin) then that would be very much preferred. Maybe you can add other admins to that account? Possibly that's a Premium-only feature. Let me know if you know more.

**Comment by cdancy** [comment] 2017-05-05 13:36
@bmuschko I believe you would have to setup the service account and give it permission to write to your repo. 

The coding part is easy enough [as it's what I do in my own projects](https://github.com/cdancy/bitbucket-rest/blob/master/gradle/publishing.gradle#L68).

**Comment by bmuschko** [comment] 2017-05-05 13:49
@cdancy Thanks, I'll look into it. Either way I propose that you guys look into a solution that doesn't require a manual release from a developer's machine. :-)

**Comment by bmuschko** [comment] 2017-05-13 15:57
@cdancy @orzeh I added the [configuration for Travis CI](https://github.com/bmuschko/gradle-docker-plugin/blob/master/.travis.yml) for a basic build and [activated the job](https://travis-ci.org/bmuschko/gradle-docker-plugin). You can now go ahead and add the configuration you mention for using Docker for functional tests. I am not super familiar with that part so I'll leave it up to you. Please be aware that the functional tests are failing right. I'd like to ask you to fix them.

**Comment by cdancy** [comment] 2017-05-13 16:01
@bmuschko I know what the issue is. In travis, and because you're running within a container, there is no native docker instance available (least last time I checked it was this way). We have to point at the host docker daemon which is easy enough to setup. I'll take a look at this today.

**Comment by bmuschko** [comment] 2017-05-13 17:48
@cdancy @orzeh I set up Docker for Travis which also starts a private registry for testing purposes. For the relevant tests I took away the `TestCondition` that checks for the existence of that private registry. Feel free to reactive if you want that check for local builds. As far as I could tell the check didn't work properly. Maybe because `http` is replaced with `tcp` [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/testSetup/groovy/com/bmuschko/gradle/docker/TestPrecondition.groovy#L11).

**Comment by cdancy** [comment] 2017-05-13 22:31
Think the better idea would be to start a private registry locally for functionalTests to run against. Shouldn't be bad at all I don't think.

**Comment by bmuschko** [comment] 2017-05-13 22:39
@cdancy Would need to be documented though so external contributors know about it. Otherwise their tests will just fail and they might think it's happening because of their changes.

**Comment by cdancy** [comment] 2017-05-13 23:02
@bmuschko oh yeah absolutely.

**Comment by bmuschko** [comment] 2017-05-14 12:57
@cdancy @orzeh I haven't found a way to create a service account for Bintray that allows access to my repositories. Adding members to my account seems to be a paid Premium feature. Creating a new organization and adding members would work but then we'd start from scratch and wouldn't have access to previous versions. Do you have any other ideas?

**Comment by cdancy** [comment] 2017-05-14 14:33
@bmuschko what if we start doing snapshot releases? So every successful PR/commit would be a potential SNAPSHOT release and only when we change the version from `X.X.X-SNASPHOT` to `X.X.X` would the repo change and we get a "real" release if you will. You could then code in your credentials/account to travis (either through properties or env vars) to make this work for every commit. 

Other than sharing your credentials, or literally making your account a service account with generic creds, I don't see another path forward until the various CI solutions provide "stage like" features that we currently have.

**Comment by cdancy** [comment] 2017-05-17 20:02
So the 400 pound gorilla in the room must be talked about: how are we going to do releases now? I gave a suggestion above which could work. I know that travis-ci has the idea of stages now which may be of some help for us assuming it can be made to work like our previous CI solution.

Any other ideas?

**Comment by bmuschko** [comment] 2017-05-17 20:54
@cdancy Sorry, simply didn't have time to respond. There are various options we have:

1. Travis CI is planning to provide manual build steps. Sounds great but I have not idea when it's going to be ready. I guess that's not really an option.
2. We set up Travis CI to deploy whenever the version of the plugin _does not_ contain the suffix `-SNAPSHOT`. We'd have to make sure that another task (or script) is put into place that adds `-SNAPSHOT` back to the version. For that purpose the version should probably rather live in a separate file.
3. Same as 2. but use a timestamp instead. You know that I am not a fan of SNAPSHOT versions. ;-)
4. Set up an organization on Bintray, choose a different group for the publication and share that key. Likely won't work as the Gradle plugin portal doesn't sync with Bintray anymore (I think).
5. Do not publish to JCenter/Maven Central anymore. Just directly publish to the Gradle plugin portal.
6. I do all the releases. Won't happen. :-)
7. Find another CI provider that provides manual steps that we just use for the purpose of releasing.

These are all the option I could come up with. I believe 2. and 3. will be the most promising though they will require some work.

**Comment by cdancy** [comment] 2017-05-17 21:03
@bmuschko I think #2 could suffice. Taking it a step further: I don't think we need to put any code/automation in place to re-commit the next development version but instead leave that up to the individual (unless there is a stupid-simple way to do so which there may be) after a release is triggered. Worst case scenario: if the property is left as a release version, say `3.0.10`, and someone triggers a job, publishing to bintray will fail (I speak from experience here) as a version already exists. Because this pops the Travis job will pop as well giving us the heads up to flip it back.

Someone or some project must have solved this problem and/or wrapped things up in an easy to use library/plugin. Seems like a thing every project has to do. I'll poke around and see if I can find anything. Until then ... the above I think will suffice for now.

**Comment by cdancy** [comment] 2017-05-17 21:07
But either way ... care to kick the `release` task now and bump the version? :)

**Comment by orzeh** [comment] 2017-05-17 21:18
Regarding option no. 2 we can use versioning plugin - [Gradle Git](https://github.com/ajoberstar/gradle-git) for example to _automate_ adding SNAPSHOT to version.

**Comment by bmuschko** [comment] 2017-05-17 21:38
I haven't looked deeper but the Mockito project does something like it: https://github.com/mockito/mockito-release-tools.

> But either way ... care to kick the release task now and bump the version? :)

I can do it quick. Next time has to work with Travis though. The code doesn't look ready though. Release notes say 3.0.7. The version is 3.0.6.

**Comment by cdancy** [comment] 2017-05-17 21:53
@orzeh have you played with it before and/or have something in mind? Send in a PR!

**Comment by cdancy** [comment] 2017-05-17 21:55
@bmuschko didn't bump the version as I assumed you could just as easily do so :)

Everything else is set and I can update the RELEASE NOTES. Nothing else we want to get in.

**Comment by bmuschko** [comment] 2017-05-17 22:11
@orzeh FYI: This plugin is already using Gradle Git: https://github.com/bmuschko/gradle-docker-plugin/blob/master/gradle/release.gradle

**Comment by bmuschko** [comment] 2017-05-17 22:28
@cdancy It has been released. I also touched up the [Snap CI job](https://app.snap-ci.com/bmuschko/gradle-docker-plugin/branch/master) by removing functional tests. In the meantime you'll be able to release with that.

**Comment by orzeh** [comment] 2017-05-17 22:33
@bmuschko yes I know, but I thought about `org.ajoberstar.release-opinion` and automatic [version inference](https://github.com/ajoberstar/gradle-git/wiki/Release%20Plugins#version-inference).

**Comment by cdancy** [comment] 2017-05-18 00:28
@orzeh looks like that could be useful.

@bmuschko new version was published to bintray but looks like github was skipped?

**Comment by bmuschko** [comment] 2017-05-18 00:45
@cdancy done

**Comment by cdancy** [comment] 2017-05-18 13:52
@orzeh I like the idea of getting the version based off of the git tag. We're actually putting together something similar here but it seems there is already code to do this very thing ;) We already tag for release so it seems like this would be easy enough to wire up for purposes.

**Comment by orzeh** [comment] 2017-05-19 08:50
@cdancy @bmuschko I've created branch [RELEASE-WORKFLOW](https://github.com/bmuschko/gradle-docker-plugin/tree/RELEASE-WORKFLOW) which:
* uses `org.ajoberstar.release-opinion` plugin to infer project version and create tags
* add `.travis.yml` release [stage](https://docs.travis-ci.com/user/build-stages/) which uploads to Bintray when on Git tag

Proposed workflow:

1. Developer updates `README.md` and `RELEASE_NOTES.md` with new version and commits locally
2. runs `release` task: `./gradlew release -Prelease.stage=final -Prelease.scope=patch` which pushes commit and new tag
3. Travis builds binaries and uploads to Bintray

@bmuschko did you add your Bintray credentials as [secure variables](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) in Travis? 

I have to also update GhPages setup, so @bmuschko please take a look at it.

WDYT?

**Comment by cdancy** [comment] 2017-05-19 14:42
@orzeh I like the idea. The only thing I would add, or maybe ask, is that you create a top level folder, maybe named `documentation`, and within it a file called `RELEASE.md` which documents this process and what each variable means. Just incase we are not around one day, and maintaining this project has fallen to others, they will know what to do. I've seen lots of projects take this approach by creating a `documentation` folder with various `*.md` files within describing/explaining various "high level" details about said project.

**Comment by orzeh** [comment] 2017-05-19 20:52
@cdancy ok, I will try to do this.

**Comment by bmuschko** [comment] 2017-06-11 23:47
@orzeh Thanks for putting together the change. I added a couple of questions for better understanding some of the functionality. I think it's worth create a PR for it and releasing a new version with this process.

**Comment by orzeh** [comment] 2017-06-12 07:24
@bmuschko thanks for your feedback. I will write some docs and make PR soon.

**Comment by bmuschko** [comment] 2017-06-28 18:29
@orzeh Were you planning to create the PR soon?

**Comment by orzeh** [comment] 2017-06-29 08:45
@bmuschko I plan to do it [tomorrow](https://github.com/blog/2386-contribute-on-open-source-friday) :smile:

**Comment by bmuschko** [comment] 2017-06-29 17:09
@orzeh Great. I was also wondering how the mechanism would determine if the next version should be a patch, minor or major version. Probably something you'd need to implement as custom versioning strategy. Something to consider when putting together the PR.

**Comment by orzeh** [comment] 2017-06-30 11:58
@bmuschko @cdancy I made a PR. Please review the documentation and overall process.

**Comment by cdancy** [comment] 2017-07-25 12:48
Closing this ISSUE as I believe we've gotten things to a stable point. Feel free to re-open if necessary or just ping on gitter.

**Closed by cdancy** 2017-07-25 12:48 UTC
Labels: enhancement, question
