### ISSUE TITLE
DockerPushImage cause error on Amazon EC2 instance

### ISSUE THREAD

**Issue by staleks** [bmuschko/gradle-docker-plugin#72] opened 2015-05-20 15:33 UTC
Hi,

I have gradle project and I've enabled gradle docker plugin for this project.
``` 
buildscript{
	repositories{
		mavenCentral()
	}
	dependencies{
		classpath 'com.bmuschko:gradle-docker-plugin:2.3.1'
	}
}
apply plugin: 'com.bmuschko.docker-remote-api'
```

Following tasks are performed:
- copy final JAR file to /src/main/docker/app (in that folder I have already prepared Dockerfile)
- making an image also works (DockerBuildImage)
- then follows tag (DockerTagImage) also works

final step is pushing image to `private docker registry`, which fails

Following error is shown (--stacktrace)

```
20-May-2015 17:21:41	:uploadAppDockerImage FAILED
20-May-2015 17:21:41	
20-May-2015 17:21:41	FAILURE: Build failed with an exception.
20-May-2015 17:21:41	
20-May-2015 17:21:41	* What went wrong:
20-May-2015 17:21:41	Execution failed for task ':uploadAppDockerImage'.
20-May-2015 17:21:41	> org.gradle.api.GradleException (no error message)
20-May-2015 17:21:41	
20-May-2015 17:21:41	* Try:
20-May-2015 17:21:41	Run with --info or --debug option to get more log output.
20-May-2015 17:21:41	
20-May-2015 17:21:41	* Exception is:
20-May-2015 17:21:41	org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':uploadAppDockerImage'.
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
20-May-2015 17:21:41	        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
20-May-2015 17:21:41	        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:310)
20-May-2015 17:21:41	        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
20-May-2015 17:21:41	        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
20-May-2015 17:21:41	        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
20-May-2015 17:21:41	        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
20-May-2015 17:21:41	        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
20-May-2015 17:21:41	        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
20-May-2015 17:21:41	        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
20-May-2015 17:21:41	        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
20-May-2015 17:21:41	        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
20-May-2015 17:21:41	        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
20-May-2015 17:21:41	        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
20-May-2015 17:21:41	        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
20-May-2015 17:21:41	        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
20-May-2015 17:21:41	        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
20-May-2015 17:21:41	        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
20-May-2015 17:21:41	        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
20-May-2015 17:21:41	        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
20-May-2015 17:21:41	        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
20-May-2015 17:21:41	        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
20-May-2015 17:21:41	        at org.gradle.launcher.Main.doAction(Main.java:33)
20-May-2015 17:21:41	        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
20-May-2015 17:21:41	        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
20-May-2015 17:21:41	        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
20-May-2015 17:21:41	        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
20-May-2015 17:21:41	        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
20-May-2015 17:21:41	
20-May-2015 17:21:41	BUILD FAILED
```

**Comment by staleks** [comment] 2015-05-20 15:35
Please note that, same procedure from my local machine is running fine.

Gradle 2.4
I am using Bamboo (with gradle wrapper support)

**Comment by bmuschko** [comment] 2015-05-21 12:22
In the stack trace I don't see any of my classes. To me this seems to be a completely different issue.

Questions:

- How do you invoke Gradle on the command line in Bamboo (specifically what command line options do you use)?
- Are you using the daemon?
- Are you executing the tasks with the tooling API by any chance?

**Comment by staleks** [comment] 2015-05-21 12:43
Hi,

1.)
as I said there are no difference between executing command from command line on my local machine and command in Bamboo ElasticNode.

Command is:
./gradlew uploadAppDockerImage

part of build.gradle follows:
```
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
task uploadAppDockerImage(type: DockerPushImage) {
   dependsOn tagAppDockerImage
  
   imageName = "private.docker.registry:5000/repo_name"
   tag = "${version}"
}
```

2.) No, I am not using daemon

3.) "Am I executing tasks with the tooling API?" <<< what do you mean by this ?
 Any example?

Thnx

**Comment by bmuschko** [comment] 2015-05-21 13:13
Maybe Bamboo is using the tooling API under the covers to execute your Gradle build. If that's the case then it uses the Daemon by default which might change things. Do you have other Gradle builds that work properly with Gradle 2.4 on Bamboo? If yes, then I don't know what the issue is. The error message doesn't give me much information on what could have gone wrong. It might be a bug in Gradle core but I have no idea what the root cause is. You might want to execute the build with `-d` to get more information.

**Comment by bmuschko** [comment] 2015-07-18 15:20
Sorry, I don't know how to help here. I am going to close the issue.

**Closed by bmuschko** 2015-07-18 15:20 UTC
