### ISSUE TITLE
build context doesn't support exclamation (aka exclusions) mark in .dockerignore

### ISSUE THREAD

**Issue by draeron** [bmuschko/gradle-docker-plugin#325] opened 2017-01-05 22:01 UTC
As per the [specification here](https://docs.docker.com/engine/reference/builder/#/dockerignore-file)

For example, this should exclude all files but include the Dockerfile and a jar file.
```
*
!Dockerfile
!some/path/to/a/file.jar
```

the docker host will start building the image but will fail since the jar file will not be in the context sent to 
```
Execution failed for task ':image'.
> Could not build image: lstat some/path/to/a/file.jar: no such file or directory
```

I know there was some issue in [docker-java](https://github.com/docker-java/docker-java/issues/286) but that was fixed a while ago already but it might be a regression too.

**Comment by orzeh** [comment] 2017-01-09 10:09
@draeron I'm using `.dockerignore` with exclusions in my projects and didn't encounter any issues.

Can you prepare sample project which demonstrates the problem?

**Comment by draeron** [comment] 2017-01-09 19:26
here's a sample project : https://github.com/draeron/helloworld. The image will build when using the docker cli but won't when using gradle.

From what i can see, the problem only affect exclusion lines with a path. so  `!some/path/to/a/file.jar` will not work but `!file.jar` will.

I did a workaround by copying necessary files into the same folder (so creating a simple context folder) and then editing path in my dockerfile.

**Comment by orzeh** [comment] 2017-01-10 12:22
@draeron I've cloned your repo and was unable to reproduce the issue:
````console
00058079mb:/tmp/helloworld$ ./gradlew image
::compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:jar UP-TO-DATE
:assemble UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:image
Building image using context '/tmp/helloworld'.
Using tag 'helloworld' for image.
Step 1 : FROM openjdk:8u92-jre-alpine
---> bd8e525f9770
Step 2 : MAINTAINER John Doe <jdoe@joe.com>
---> Running in 5fd62192e331
---> a7339c9bf71c
Removing intermediate container 5fd62192e331
Step 3 : COPY build/libs/*.jar hello.jar
---> 11bef39ebecc
Removing intermediate container 466d1513e6b3
Step 4 : ENTRYPOINT java -jar hello.jar
---> Running in 320c5aae9186
---> 898004086975
Removing intermediate container 320c5aae9186
Successfully built 898004086975
Created image with ID '898004086975'.

BUILD SUCCESSFUL

Total time: 47.323 secs
````

**Comment by draeron** [comment] 2017-01-10 15:18
are you on windows? might it be a \ or / issue ?

**Comment by orzeh** [comment] 2017-01-11 07:33
I'm on Linux. 

Did you double check that `some/path/to/a/file.jar` exists and it is in build context?

**Comment by draeron** [comment] 2017-01-11 18:44
i just made some test, this only happen on windows, on linux it will work properly. So it has to do with the path. Do you think the problem might in [docker-java](https://github.com/docker-java/docker-java) ?

**Comment by orzeh** [comment] 2017-01-12 10:25
> Do you think the problem might in docker-java ?

@draeron probably yes, because we delegate `.dockerignore` handling to it.

Maybe try to run their tests on Windows and see if something breaks. Then report an issue.

**Comment by cdancy** [comment] 2017-05-14 21:07
Closing as this is more a docker-java issue than anything else IMO. Feel free to re-open if necessary.

**Closed by cdancy** 2017-05-14 21:07 UTC
