### ISSUE TITLE
inputDir not working

### ISSUE THREAD

**Issue by marbon87** [bmuschko/gradle-docker-plugin#187] opened 2016-03-30 09:00 UTC
Hi,

i created the following gradle tasks to create a dockerfile and build a image from it:
```
task testBaseDockerfile(type: Dockerfile){
    ext.dockerImageName = 'test-base'
    destFile = project.file('./build/dockerfiles/' + ext.dockerImageName + '/Dockerfile')
    from(baseImage.dockerImageName + ":" + baseImage.dockerImageVersion)
    maintainer('me')
    addFile("./" , "/opt")
}

task testBaseImage(type: DockerBuildImage){
    dependsOn testBaseDockerfile
    inputDir = project.projectDir
    dockerFile = project.file('./build/dockerfiles/' + testBaseDockerfile.dockerImageName + '/Dockerfile')
    tag = testBaseDockerfile.dockerImageName + ':' + jar.version
}
```

I want to create a docker-image, that contains the whole project to run gradle tasks inside the docker-container. So i added the command ```addFile("./" , "/opt")```. The problem is that only the files from ```./build/dockerfiles/test-base```are added to the context and to the docker-image. The container, that is created from the dockerfile, has only following content:
```
root@7f3a7e5fe1ff:/opt# tree
.
└── build
    └── dockerfiles
        └── test-base
            └── Dockerfile

```

I also tried the current master with docker-java 2.2.3, but the problem is the same.

**Comment by orzeh** [comment] 2016-03-30 09:26
Maybe you have some `.dockerignore' file?

BTW, it would be more efficient to use Docker volumes to add project sources to the container.

**Comment by marbon87** [comment] 2016-03-30 09:31
There is no ```.dockerignore``` 

Regarding to volumes: maybe you are right, but i want a isolated environment including files

**Comment by cdancy** [comment] 2016-03-30 18:58
@marbon87 I assume this works exactly the same outside of this plugin as well? Have you tried taking a peak at the generated Dockerfile, edit it how you want, and then see if it works running everything from the same directory? 

I think you are trying to add files outside of the scope from where the Dockerfile is being run. I believe it expects all files to be relative to it or at least children of the folder the Dockerfile is in. You may want to copy the relevant files into the same folder as your Dockerfile or at least into some sub-folder to get picked up.

**Comment by marbon87** [comment] 2016-03-31 06:07
@cdancy the Dockerfile, that is created is correct, but the image does not contain the correct files.
I thought that i could configure arbitrary path with the ```inputDir = ...``` as the docker context. The docs only say ```Input directory containing the build context.```

**Comment by cdancy** [comment] 2016-03-31 11:07
@marbon87 have you tried putting those files relative to the created Dockerfile to see if that works? I've never not done that before so I've never bumped into your issue.

**Comment by cdancy** [comment] 2016-03-31 11:10
@marbon87 also you may want to try a path that is more absolute. From dockers point of view, when it executes the Dockerfile, it's looking at your './' and resolving that to the current directory.

**Comment by marbon87** [comment] 2016-03-31 11:12
@cdancy files, that are in the same folder as the Dockerfile are added to the Image
Absolute path does not work either

**Comment by cdancy** [comment] 2016-03-31 11:17
@marbon87 that makes sense. [Looking over the Dockerfile documentation for the ADD instruction](https://docs.docker.com/engine/reference/builder/) this is expected behavior.

> The <src> path must be inside the context of the build; you cannot ADD ../something /something, because the first step of a docker build is to send the context directory (and subdirectories) to the docker daemon.

**Comment by orzeh** [comment] 2016-03-31 11:19
@cdancy 
> From dockers point of view, when it executes the Dockerfile, it's looking at your './' and resolving that to the current directory.

It is not true, because @marbon87 set Docker build context dir explicitly via:
` inputDir = project.projectDir`
Note that in resulting image, there is directory tree with Dockerfile, so `./` was interpreted correctly, however other project files are missing.

**Comment by cdancy** [comment] 2016-04-11 02:21
@marbon87 are you all set here? Were you able to move forward?

**Comment by marbon87** [comment] 2016-04-12 07:02
No. Temporary i am working always in the root folder of the project and selecting files from there.

**Comment by PatrickHuetter** [comment] 2016-04-25 10:21
Same problem here. There is a bug with inputDir. It's not working as expected. I can't have the Dockerfile and the context in different directories because inputDir will always point to the folder of the Dockerfile and not to the in the configuration specified folder.

**Comment by cdancy** [comment] 2016-04-25 11:09
@PatrickHuetter @marbon87 you guys may want to open up an [issue with docker-java](https://github.com/docker-java/docker-java). All we are doing is forwarding the parameters to them, it's their library which is actually doing the work in this context.

**Comment by PatrickHuetter** [comment] 2016-04-25 12:45
I don't know wether the referenced issue is the correct one but i think this is the same problem we have and our use case seems to be not implemented yet.

**Comment by llamahunter** [comment] 2016-04-25 13:31
You *can* specify a Dockerfile that is a) not called 'Dockerfile', and b) somewhere not at the root of the inputDir.  But, due to restrictions on the way docker-java works, it must be contained within the inputDir subtree.

**Comment by PatrickHuetter** [comment] 2016-04-25 13:33
@llamahunter so b) seems to be the problem here and as you said it's not possible and it sounds like it won't be possible the next time. So i changed my build configuration to contain the Dockerfile within the inputDir. Thank you very much!

**Comment by cdancy** [comment] 2016-05-10 15:49
Closing issue. Problem lies with docker-java and an issue is already open. For now folks will have to put all resources relative to the Dockerfile in question.

**Closed by cdancy** 2016-05-10 15:49 UTC
