### ISSUE TITLE
Documentation links are broken for DockerSaveImage and DockerLoadImage

### ISSUE THREAD

**Issue by conorgriffin** [bmuschko/gradle-docker-plugin#567] opened 2018-04-03 13:04 UTC
The links to docs for these two tasks result in 404s from the project README section on images here: https://github.com/bmuschko/gradle-docker-plugin#images

**Comment by cdancy** [comment] 2018-04-03 13:33
@conorgriffin thanks for pointing this out or rather opening an ISSUE to track this known bug. Since we switched to a new release process our github-pages docs-branch hasn't been updated and we need to fix it.

@orzeh does anything initially stick out to you?

**Comment by orzeh** [comment] 2018-04-05 07:24
@cdancy I was able to reproduce the issue we can observe in logs on travis, however only once. Subsequent build pass without errors 😕 Will try to investigate this.

**Comment by stevendpclark** [comment] 2018-05-10 02:53
I looked into this a bit tonight, basically the documentation on the GitHub site hasn't been updated since release 3.2.1 (doc is for version 3.2.0 currently, which is why the html pages do not exist). Within the 3.2.1 release window, looks like an upgrade to Gradle 4.2 within commit 3688aabe563a553a5c33036436d3d4a8f06a142d occurred.

I believe the Gradle upgrade, triggered: https://github.com/ajoberstar/gradle-git-publish/issues/35 which has been fixed by release [0.3.2](https://github.com/ajoberstar/gradle-git-publish/releases/tag/0.3.2).

**Comment by cdancy** [comment] 2018-05-10 10:51
Yeah that might be it. I use the upgraded version on other projects I maintain with no issues to speak of. Maybe a quick version bump is all it will take.

**Comment by rm8x** [comment] 2018-05-11 19:18
Also getting a 404 when trying to reach http://bmuschko.github.io/gradle-docker-plugin/docs/groovydoc/com/bmuschko/gradle/docker/tasks/container/extras/DockerWaitHealthyContainer.html

**Comment by orzeh** [comment] 2018-05-11 20:29
@stevendpclark Thanks for your input! 

I was able to reproduce it on my local - just need to clone fresh copy. Then it always fails during the first build. 

I've bumped `gradle-git-publish` version and it works, however can't use latest since it conflicts with `gradle-git`, which we are using for versioning.

@cdancy when PR is merged you can spin a new release to give it a try.

**Closed** 2018-05-11 20:39 UTC
Labels: bug, question

**Comment by cdancy** [comment] 2018-05-11 20:50
@orzeh merged though we need at least 1 new feature to get a release in right? I feel ... weird ... doing a release to fix docs. I could be convinced otherwise though...
