### ISSUE TITLE
DockerSaveImage does not respect the tag option

### ISSUE THREAD

**Issue by gcscaglia** [bmuschko/gradle-docker-plugin#544] opened 2018-02-21 17:36 UTC
The `DockerSaveImage` task always saves all images from a repository, even when a particular tag is specified.

As a workaround, its possible to specify a complete image id (e.g. `'repository:tag'`) as the repository property to archive the desired results.

Attached bellow is a complete exemple for reproduction:

```gradle
plugins {
    id 'base'
    id 'com.bmuschko.docker-remote-api' version '3.2.4'
}

import com.bmuschko.gradle.docker.tasks.image.DockerPullImage
import com.bmuschko.gradle.docker.tasks.image.DockerSaveImage

task pullAlpine37(type: DockerPullImage) {
    repository = 'alpine'
    tag = '3.7'
}

task pullAlpine36(type: DockerPullImage) {
    repository = 'alpine'
    tag = '3.6'
}

task createOutputFile() {
    doLast {
        def target = file('build/output.tar')
        target.getParentFile().mkdirs()
        target.createNewFile()
    }
}

task prepareExample(dependsOn: [pullAlpine37, pullAlpine36, createOutputFile])

// output.tar should contain only alpine:3.7, but also contains alpine:3.6!
task saveImageFail(type: DockerSaveImage, dependsOn: prepareExample) {
    destFile = file('build/output.tar')
    repository = 'alpine'
    tag = '3.7'
}

// output.tar contains only alpine:3.7, as expected.
task saveImageOK(type: DockerSaveImage, dependsOn: prepareExample) {
    destFile = file('build/output.tar')
    repository = 'alpine:3.7'
}
```

**Comment by cdancy** [comment] 2018-02-21 17:54
@gcscaglia good catch. Care to send in a PR to address this?

**Comment by gcscaglia** [comment] 2018-02-21 19:11
@cdancy Sorry, groovy is not a strong language of mine. I've dug around, but for all I understood it's already implemented [here][1], so I don't know why it's not working. I assume this will need someone more familiar with this plug-in (and/or groovy) to pinpoint the actual issue.

[1]: https://github.com/bmuschko/gradle-docker-plugin/blob/49f4611b2575ce23dbe9ef36315a4dfe3f2660bb/src/main/groovy/com/bmuschko/gradle/docker/tasks/image/DockerSaveImage.groovy#L38-L40

**Comment by gcscaglia** [comment] 2018-03-13 20:57
Just a heads up, while investigating [another issue in the upstream](docker-java/docker-java#1005), I've stumbled upon [this PR](docker-java/docker-java#521). It seems this bug isn't actually on `gradle-docker-plugin` itself but on `docker-java` library.

**Comment by cdancy** [comment] 2018-03-13 21:18
@gcscaglia good find!

**Comment by bmuschko** [comment] 2018-10-06 17:07
We are now using the latest version of the Docker Java library. I assume this issue should be fixed. Please reopen if you find this not to be the case.

**Closed by bmuschko** 2018-10-06 17:07 UTC
Labels: enhancement

**Comment by johnyb79** [comment] 2018-10-24 12:32
Tested with gradle-docker-plugin (s) > 3.6.0, and  still  does not work for me,

**Comment by bmuschko** [comment] 2018-10-24 13:36
@johnyb79 What specific version did you try? You will need at least v3.6.2 which upgraded to Docker Java 3.1.0-rc-5.

**Comment by johnyb79** [comment] 2018-10-24 13:46
Thanks for reply !
 > 3.6.0, so 3.6.2, 4.0.0, 4.0.1. The workaround with 'repository:tag' used in task (type: DockerSaveImage ...) works indeed. 
I have defined in my build.gradle 3 tasks (I think is a common usage) DockerPullImage -> DockerTagImage -> DockerSaveImage

**Comment by robbie-demuth** [comment] 2018-11-08 14:43
I'm running v4.0.4 and this still seems to be an issue. I'm not sure if it was fixed in an earlier version and broken again though

**Comment by bmuschko** [comment] 2018-11-08 14:51
@robbie-demuth Could you please create a new issue with some sample code you expect to work?

**Comment by robbie-demuth** [comment] 2018-11-08 15:48
I created https://github.com/bmuschko/gradle-docker-plugin/issues/703, though it is pretty much an exact duplicate of this issue
