### ISSUE TITLE
3.0.11 / latest release is not on gradle registry.

### ISSUE THREAD

**Issue by javadevmtl** [bmuschko/gradle-docker-plugin#421] opened 2017-07-22 02:29 UTC
Hi, see: https://plugins.gradle.org/plugin/com.bmuschko.docker-remote-api

Same for the application plugin: https://plugins.gradle.org/plugin/com.bmuschko.docker-java-application

**Comment by jordanjennings** [comment] 2017-07-25 04:08
This is a duplicate of #411

**Comment by cdancy** [comment] 2017-07-25 10:13
Latest release is 3.0.12 and can be sourced from jcenter/maven. The 3.0.11 release was not perfect due to us trying a new release process. Issue has since been fixed and the next release will be 3.1.0.

**Closed by cdancy** 2017-07-25 10:13 UTC
