### ISSUE TITLE
How to use plugin authentication to push to external registry?

### ISSUE THREAD

**Issue by patton73** [bmuschko/gradle-docker-plugin#991] opened 2021-03-11 16:20 UTC
Good evening, 

I am opening this bug because i am not able to push an image on an external docker repository that requires authentication.
I am using latest plugin version 6.7.0.

Here the snippet of the code i use:

```
task createImage(type: DockerBuildImage) {            
    dependsOn assemble
    inputDir = project.rootDir
    images.add("domain/myapp:${versione}")
}
```

```
task publishImageOnRegistry(type: DockerPushImage, dependsOn: createImage) {      
    images.add("domain/myapp:${versione}")   
    registryCredentials.with {
        url.set('registryURL in https')
        username.set('USERNAME')
        password.set('USER PASSWORD')
        email.set('EMAIL')
    }
}
```

"versione" is a well defined variable.

I have read all the bugs related to this topic but i still cannot publish on the registry.
I also searched the documentation but found no working example yet.
I always get: Could not push image: unauthorized: incorrect username or password

Is there a correct way to let the DockerPushImage task to authenticate and push the image?
In addiction, with same credential "docker login" from command line  works and I am able to push the 
image to the repository by hand.

Thank you in advance for any help you can provide.

**Comment by bmuschko** [comment] 2021-03-17 02:23
What kind of custom registry (e.g. Artifactory, GCR, ACR, ECR are we talking about here? Can you clarify as the notation is different. The registry credentials are not relevant to the image name. They are only used for connecting to the Docker daemon. Just wanted to point that out.

**Comment by patton73** [comment] 2021-03-17 07:09
Thanks for the reply. I was trying to publish an image over an intranet system registry, in my case it is Harbor.
Anyway i managed to authenticate against the registry this way.

task publishOnRegistry(type: DockerPushImage, dependsOn: tagImage) {      
    doFirst {
        docker.registryCredentials {
            url = "https://REGISTRYURL/"
            username = 'USERNAME'
            password = 'PASSWORD'
            email = 'EMAIL'
        }
    }
    images.add("CORRECTSTRING-TO-PUBLISH-IMAGES")   
}

My problem was that I could never override default registry values.
Using the doFirst {} solved the problem.

I could not find no other way. 
Even documentation's way does not work.
Defining this does nothing.

docker {
    registryCredentials {
        url = 'URL'
        username = 'USERNAME'
        password = 'PWD'
    }
}

 Or pheraps (very likely) I did not understand what's meant to do the previous code.
Anyway thaks a lot for your answer.
Warm regards.

**Comment by bmuschko** [comment] 2021-03-17 14:02
This should work without `doFirst`. Using `doFirst` is actually incorrect except if there's a bug in the plugin that doesn't properly execute the logic at the right time.

**Comment by patton73** [comment] 2021-03-17 16:48
No if you do not use `doFirst` it does not work. The only way to let it work is using `doFirst`.
regards.

**Comment by bmuschko** [comment] 2021-03-17 16:52
Then that's a bug. I'd need to check the test cases but would be happy if somebody from the community could look into it and provide a PR.

**Comment by bmuschko** [comment] 2021-04-30 13:55
I am not quite sure what's going on in your project. In general, this should as demonstrated in those test cases: https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/functTest/groovy/com/bmuschko/gradle/docker/DockerRemoteApiPluginFunctionalTest.groovy.

I'd need to see a minimal, sample project the reproduces the issue. I am going to close this for now. We can reopen if you can provide a sample project.

**Comment by patton73** [comment] 2022-02-22 10:19
Since docker.registryCredentials does not override anything and does not exec the login with correct credentials I solved the problem this way. 

task publish(type: DockerPushImage) {
    doFirst {
        exec {
            def url = "https://url"
            def username = "username"
            def password = "password"
            executable "bash"
            args "-c", "docker login -u ${username} -p ${password} ${url}"
        }
    }
    images.add(....")
}

I anyway recommend you to fix the problem with RegistryCredentials' semantics.
Warm regards.

**Comment by bmuschko** [comment] 2022-03-02 23:36
I added a functional test case that demonstrates how to push an image to the Harbor demo server: https://github.com/bmuschko/gradle-docker-plugin/commit/4784481db450b1a88e17c3dd24f1c53b704e43b6. I cannot reproduce your issue. Have a look at the test case and maybe compare it with what you have. If you still can't figure it out, I'd need to see your full build script as a reproducible example.

**Closed by bmuschko** 2022-03-02 23:36 UTC
Labels: bug

**Comment by SinghDivneet** [comment] 2022-09-27 13:16
I am running into a similar issue to pull an image from harbour & defining the following does nothing for me.

```docker {
  registryCredentials {
    url = ironbankDockerRegistryUrl
    username = ironbankDockerRegistryUsername
    password = ironbankRegistryPassword
    email = ironbankDockerRegistryEmail
  }
}
