### ISSUE TITLE
'java.lang.reflect.InvocationTargetException-->null' error on buildImage default build.

### ISSUE THREAD

**Issue by st9x3st9** [bmuschko/gradle-docker-plugin#185] opened 2016-03-22 16:28 UTC
I am using the default example for building a docker container
```
task createDockerfile(type: Dockerfile) {
    destFile = project.file('build/mydockerfile/Dockerfile')
    from 'ubuntu:12.04'
    maintainer 'Benjamin Muschko "benjamin.muschko@gmail.com"'
}

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    inputDir = createDockerfile.destFile.parentFile
    tag = 'bmuschko/myimage'
}
```
but I am receiving a 
```
Execution failed for task ':buildImage'.
> java.lang.reflect.InvocationTargetException-->null
```
error message on the gradle build command. This seems like a bug. I am using gradle 2.11 by the way.

**Comment by cdancy** [comment] 2016-03-22 16:37
@st9x3st9 which version of the plugin are you using? Does running gradle with '-i' give any more information?

**Comment by st9x3st9** [comment] 2016-03-22 16:42
I am using version 2.6.7.

**Comment by cdancy** [comment] 2016-03-22 16:44
@st9x3st9 and what about running with '-i' to get additional information? Can we see those logs? Can we see your full gradle script as well?

**Comment by st9x3st9** [comment] 2016-03-22 16:45
Is there an example project that you know of that I can look at to see what is being done differently?

**Comment by cdancy** [comment] 2016-03-22 16:48
@st9x3st9 you can look through any of the [functional tests](https://github.com/bmuschko/gradle-docker-plugin/tree/master/src/functTest/groovy/com/bmuschko/gradle/docker) we have and model your own code after that.

**Comment by st9x3st9** [comment] 2016-03-22 17:07
I meant an example gradle config that has this running. Do you have any idea where the `java.lang.reflect.InvocationTargetException-->null` error would be coming from?

**Comment by orzeh** [comment] 2016-03-22 17:12
@st9x3st9 show your `build.gradle`!
Are there any other errors in build output? Show us console log with -i switch.
Does your docker engine is up and running? Do you use local or remote engine?
Provide some context!

**Comment by st9x3st9** [comment] 2016-03-22 18:57
So I created a gist of the basics of what I am doing https://gist.github.com/st9x3st9/e77c06c6e087a3371e6d. Sorry this is for a private repository so I can not post the full build.gradle file. Could you see there being conflicts for this plug-in with other projects.

**Comment by st9x3st9** [comment] 2016-03-22 18:58
If anyone has a link to a full project they implemented that I can look over, so I can check versions, gradle configs, etc. That would be much appreciated.

**Comment by cdancy** [comment] 2016-03-22 19:01
@st9x3st9 any particular reason you're adding the plugin to your [compile time](https://gist.github.com/st9x3st9/e77c06c6e087a3371e6d#file-build-gradle-L15) dependencies?

You still haven't posted your output when running with the '-i' flag. Without that I'm afraid there is not much more we can do.

**Comment by st9x3st9** [comment] 2016-03-22 20:02
I am adding the compile time dependencies because otherwise it will not import the individual class files like Dockerfile, here is the end of the stacktrace.
```
:build (Thread[main,5,main]) started.
:build
Skipping task ':build' as it has no actions.
:build (Thread[main,5,main]) completed. Took 0.0 secs.
:createDockerfile (Thread[main,5,main]) started.
:createDockerfile
Executing task ':createDockerfile' (up-to-date check took 0.001 secs) due to:
  Task.upToDateWhen is false.
:createDockerfile (Thread[main,5,main]) completed. Took 0.016 secs.
:buildImage (Thread[main,5,main]) started.
:buildImage
Executing task ':buildImage' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Building image using context '/Users/abalz1/Work/nike/code/notificationeventproc/build/mydockerfile'.
Using Dockerfile '/Users/abalz1/Work/nike/code/notificationeventproc/build/mydockerfile/Dockerfile'
Using tag 'bmuschko/myimage' for image.
Running in a non-OSGi environment
"No custom request executor provider registrations found - using default: [org.glassfish.jersey.client.ClientAsyncExecutorFactory$1]."
:buildImage FAILED
:buildImage (Thread[main,5,main]) completed. Took 1.213 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildImage'.
> java.lang.reflect.InvocationTargetException-->null

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildImage'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:158)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:155)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:36)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:103)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:102)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: net.sf.cglib.proxy.UndeclaredThrowableException: java.lang.reflect.InvocationTargetException-->null
	at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$6b522a0c.awaitImageId(<generated>)
	at com.github.dockerjava.core.command.BuildImageResultCallback$$EnhancerByCGLIB$$6b522a0c$awaitImageId.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.image.DockerBuildImage.runRemoteCommand(DockerBuildImage.groovy:119)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$_start_closure1.doCall(AbstractDockerRemoteApiTask.groovy:48)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader.withClasspath(DockerThreadContextClassLoader.groovy:43)
	at com.bmuschko.gradle.docker.utils.ThreadContextClassLoader$withClasspath.call(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:53)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:47)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 60 more
Caused by: java.lang.reflect.InvocationTargetException
	at java_lang_reflect_Method$invoke.call(Unknown Source)
	at com.bmuschko.gradle.docker.utils.DockerThreadContextClassLoader$_createPrintStreamProxyCallback_closure8.doCall(DockerThreadContextClassLoader.groovy:354)
	at com.sun.proxy.$Proxy74.invoke(Unknown Source)
	... 77 more
Caused by: com.github.dockerjava.api.DockerClientException: Could not build image
	at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:69)
	at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
	... 80 more


BUILD FAILED

Total time: 41.01 secs
Stopped 0 compiler daemon(s).
```

Is it not able to build the image? If so why it seems pretty vague.

**Comment by cdancy** [comment] 2016-03-22 20:19
> I am adding the compile time dependencies because otherwise it will not import the individual class files like Dockerfile

There should be no need to do this. You've already added the project and its classes to the buildscript classpath. Adding it to the compile dependencies is doing nothing for your build script. When I write my tasks I tend not to import their classes like you do but instead just use the fully qualified name. It's easier to ready IMO and doesn't fill your script with lots of import statements.

Do you have other dependencies on your buildscript classpath that you've not noted in your sample?

**Comment by st9x3st9** [comment] 2016-03-22 20:33
scoverage, jettyEclipse are 2 of the public plugins that I have I have 7 others but they are internal tools. Why would these cause a conflict?
Also I think the error breaks down to the below line. I am seeing it for all of the docker tasks.
```"No custom request executor provider registrations found - using default: [org.glassfish.jersey.client.ClientAsyncExecutorFactory$1]."```

**Comment by cdancy** [comment] 2016-03-22 20:43
You have to remember: if there are plugins on the buildscript classpath that rely on specific versions of libraries, and the dependencies that you add override these versions, than the plugin is likely to break due to wrong class versions/etc. That's just the nature of how gradle resolves dependencies and IMO is a drawback at least when it comes to this sort of thing. We have an open PR #176 that we are currently vetting a solution around this problem so that the buildscript classpath does not leak into the plugin classpath. 

It looks like something similar is going on with your script. Here is what I would do: remove ALL dependencies, except for gradle-docker-plugin, and then get things going. Then add 1 buildscript dependency at a time until things fall over. That should give you some indication as to which dep is the culprit and breaking the plugin. I suspect it is some dependency that is bringing in a version of jersey or cglib that is not playing nicely with docker-java. Or ... you could just print out the buildscript classpath and see which version of these libraries are trying to override those required by docker-java.

**Comment by orzeh** [comment] 2016-03-22 21:43
From stacktrace I see that exception is thrown at [BuildImageResultCallback.java:69](https://github.com/docker-java/docker-java/blob/2.x/src/main/java/com/github/dockerjava/core/command/BuildImageResultCallback.java#L69) so I guess there was unexpected response from docker engine.
Try to build image using generated `Dockerfile` with docker CLI:
````sh
cd /Users/abalz1/Work/nike/code/notificationeventproc/build/mydockerfile
export DOCKER_HOST=http://192.168.1.1:2375
export DOCKER_CERT_PATH=~/.docker/machine/machines/default
docker --rm -t bmuschko/myimage build .
````

**Comment by cdancy** [comment] 2016-03-22 22:21
@st9x3st9 also ... what version of docker are you running against? docker-java only supports a sub-set of the latest API and so if you're running against that you may run into issues with the returned json not being formatted correctly which is what @orzeh may be alluding to.

**Comment by st9x3st9** [comment] 2016-03-22 22:37
@orzeh I did what you asked and it worked fine. The ports were different and I had to change it from http to tcp, but once I did that it worked perfectly, but I am still getting the same error with building the image. @cdancy I am using docker 1.10.1 build 9e83765.

**Comment by cdancy** [comment] 2016-03-22 22:41
@st9x3st9 that may be too bleeding edge at the moment. We build on top of [docker-java](https://github.com/docker-java/docker-java) and I'm not sure they support 1.10 at this point. Looking at their page it appears no or at least only minimally. I would try running against an older version of docker to see how that fares.

**Comment by st9x3st9** [comment] 2016-03-22 23:12
I moved docker back to version 1.9 and still its giving me the ```java.lang.reflect.InvocationTargetException-->null``` error. It has to be something with the ```"No custom request executor provider registrations found - using default: [org.glassfish.jersey.client.ClientAsyncExecutorFactory$1]."``` I can not figure it out. I am going to have to check for a dependency conflict, is there a easy gradle command to accomplish this?

**Comment by dklotz** [comment] 2016-03-23 16:42
I am getting the same error (or the gradle builds hangs for several minutes, seems to a bit random?!) on OS X, plugin version 2.6.7, docker version 1.10.3, gradle version 2.12. If this is indeed a problem with the old docker-java, any chance of releasing a version that uses their 3.0.0-RC3 release candidate version (which is supposed to support docker 1.10.x)? Or anything I could do to help debug this further (downgrading docker would currently be a big hurdle, sorry...)?

**Comment by cdancy** [comment] 2016-03-23 16:49
Docker 1.10.+ is quite bleeding edge at this point in time. We have it on the backlog to go to docker-java 3.0.0 but nothing is currently in the works.

@dklotz I have a feeling this is more a transitive dependency issue than anything else. Do you have other plugins/libraries on the buildscript classpath? Have you tried removing them all and seeing if your docker based tasks work?

**Comment by dklotz** [comment] 2016-03-23 17:22
Yes I had `com.netflix.nebula:nebula-dependency-recommender:3.1.0` and another internal plugin (used to setup cross-project dependency stuff etc. for our projects) as buildscript dependencies. I just tried it again with no other projects on the buildscript classpath and got the same error message. Complete log is in [this gist](https://gist.github.com/dklotz/d8a0e95a95199433a4d3). Building the generated docker image manually works without a problem.

**Comment by cdancy** [comment] 2016-03-23 18:03
@dklotz to rule out any plugin specific issues can you try with say version 2.6.4 and see what happens? I assume it will still fail but at least we know it's not a direct plugin issue but more a transitive dependency one.

**Comment by dklotz** [comment] 2016-03-24 11:09
I haven't been able to reproduce the error with 2.6.4. But after I tried that, I haven't been able to reproduce it any longer with 2.6.7 either... this is turning into a Heisenbug...

**Comment by Teudimundo** [comment] 2016-04-07 16:30
I'm not sure is the same issue, the final error is the same, but the stack trace tells me "Connection reset by peer". I use docker 1.10, if I check on the docker logs of the docker machine I can see the following error:

`2016/04/07 16:21:24 http: TLS handshake error from 192.168.99.1:49299: tls: oversized record received with length 21536`

**Comment by cdancy** [comment] 2016-04-07 16:32
@Teudimundo have you tried running against an older version of docker? 1.10 is still bleeding edge at this point.

**Comment by Teudimundo** [comment] 2016-04-07 16:53
Unfortunately we are using several features of the 1.10. In 5 days the 1.11 will be released.

I think also it should be possible  to change docker version and test one's applications against the latest.

But I fully understand that you have limited resources

**Comment by cdancy** [comment] 2016-04-07 17:49
@Teudimundo it's not so much that, it's that dockers API is unstable and changing all the time. Furthermore, this plugin builds on top of the docker-java library and so we only support what they can provide. They have a newer in-development 3.0.0 version of their library which will most likely fix a lot of issues folks are reporting but until they release it we won't rebase off an in-dev version.

Assuming it is a docker API bug, which I can't say for certain it is, it might be worth asking on the docker-java page to see what they have to say. 

But before doing so I would try the following:

1. Try to run the same workflow outside of the plugin to see if it fails
2. Remove all dependencies, other than gradle-docker-plugin, to your gradle script and see if it still fails. It's possible there is a dependency clobbering issue.
3. As noted above: try running with an older version of docker to see if that helps.

**Comment by Teudimundo** [comment] 2016-04-07 20:07
Thanks for your reply. I know that keeping up the pace with docker API is very hard, and I didn't know that 3.0.0 was still in development. 

Relatively at your suggestions, step 1 and 2 have been done I'm going to try the 3 as well.

Anyway the project is a simple hello world with no other plugin I really liked the approach of your plugin and I wanted to try it to see if it fits my needs.

This is probably a naïve question, but why there is no way of using the docker binary instead of the remote API? It looks like that Docker people put a bit more effort to assure the retro-compatibility for the CLI than the remote APIs.

**Comment by cdancy** [comment] 2016-04-07 20:44
> This is probably a naïve question, but why there is no way of using the docker binary instead of the remote API?

Just the nature of this particular plugin. There may be other plugins which code to the binary. 

Have you tried searching google for this particular issue? I've found at least 1 issue which may be helpful:

https://github.com/docker/docker/issues/14793

**Comment by cdancy** [comment] 2016-04-11 02:37
@Teudimundo were you able to move foward? I'm not sure if your issue is directly related to the one at hand. If you are still having troubles please open up another issue addressing your concerns along with a complete stacktrace and example script you are using.

**Closed by cdancy** 2016-04-11 02:37 UTC
