### ISSUE TITLE
Building images on OSX does not seem to work

### ISSUE THREAD

**Issue by mhgrove** [bmuschko/gradle-docker-plugin#143] opened 2016-01-29 15:37 UTC
The task is defined as such:

```groovy
task buildImage(type: DockerBuildImage) {
	inputDir = createDockerFile.destFile.parentFile
	tag = "myTag"
}
```

If I run this, I get a `Connection Refused` message:

> Connect to localhost:2375 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused

This makes sense, that's not where docker is running locally.  If I grab the URL from `docker-machine` and specify it as such:

```groovy
docker {
	url = "http://192.168.99.100:2376"
}
```

I can get past the `Connection Refused` message, but it still fails with a broken pipe:

```
[pool-16-thread-1] INFO org.apache.http.impl.execchain.RetryExec - I/O exception (java.net.SocketException) caught when processing request: Broken pipe
[pool-16-thread-1] ERROR com.github.dockerjava.core.async.ResultCallbackTemplate - Error during callback
org.apache.http.client.ClientProtocolException
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:188)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.github.dockerjava.jaxrs.connector.ApacheConnector.apply(ApacheConnector.java:441)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:246)
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:683)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:424)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:679)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:435)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:338)
	at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:45)
	at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:102)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	... 18 more
Caused by: java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:123)
	at org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:135)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:164)
	at org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:175)
	at org.apache.http.impl.io.SessionOutputBufferImpl.writeLine(SessionOutputBufferImpl.java:213)
	at org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:125)
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:181)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
	at org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:114)
	at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:77)
	at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
	at org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:301)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1154)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:503)
	at com.github.dockerjava.jaxrs.connector.ApacheConnector$2.writeTo(ApacheConnector.java:576)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.http.impl.execchain.RequestEntityExecHandler.invoke(RequestEntityExecHandler.java:77)
	at com.sun.proxy.$Proxy382.writeTo(Unknown Source)
	at org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy383.sendRequestEntity(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:253)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:194)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:85)
	... 20 more
```

Is the plugin not supported on OSX or am I not configuring it correctly?

**Comment by cdancy** [comment] 2016-01-29 15:53
The plugin can be run from anywhere as its using dockers remote API so that shouldn't be a problem. Support for docker on OSX was flaky in the past and I'm not entirely sure where things stand today. Here are a few things we can look at:

Which version of docker are you using?
Can you successfully ping the docker url? (e.g. http://192.168.99.100:2376/_ping)

**Comment by mhgrove** [comment] 2016-01-29 16:13
I'm using 1.9.1, on OSX 10.10.5

Yep, I get a response from the ping URL; wget returned me a binary response.

**Comment by cdancy** [comment] 2016-01-29 16:17
What do you mean by "binary response"? Pinging that URL should have given you an "Ok"...

**Comment by mhgrove** [comment] 2016-01-29 16:26
I pinged:
```
ping http://192.168.99.100:2376/_ping
ping: cannot resolve http://192.168.99.100:2376/_ping: Unknown host
```

Which didnt work out, but doing a `wget` on the URL returned some binary.

This is what I get from `docker-machine`:

```
docker-machine ls
NAME      ACTIVE   URL          STATE     URL                         SWARM   DOCKER   ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v1.9.1   
```

**Comment by gesellix** [comment] 2016-01-29 16:34
did you configure the `DOCKER_CERT_PATH`?

**Comment by gesellix** [comment] 2016-01-29 16:37
regarding the ping, you have to run it like this:

    ping 192.168.99.100

**Comment by cdancy** [comment] 2016-01-29 16:40
Ping may have been the wrong terminology here. You can either use a wget or simply paste the url into your browser. If docker does not return an "OK" it means you can't connect to the daemon and have things configured wrongly.

**Comment by gesellix** [comment] 2016-01-29 16:47
By default the docker-machine/boot2docker uses TLS, so that a simple curl/wget won't work without using the certificates. That's why I asked whether the `DOCKER_CERT_PATH` is configured. Its value should probably also be configured in the `docker {}` plugin config.

**Comment by mhgrove** [comment] 2016-01-29 16:48
no, I didnt set `DOCKER_CERT_PATH`.

Yeah, if I paste the ping URL into my browser, I get a 7 byte binary file rather than "OK".

@gesellix I thought boot2docker was no longer used on osx.  It's certainly not installed on my system.

**Comment by gesellix** [comment] 2016-01-29 17:10
If you run `docker-machine env default` you'll see whether a `DOCKER_CERT_PATH` is set. I suggest to copy the shown path to your Gradle file like this:

```
docker {
   url = "http://192.168.99.100:2376"
   certPath = "/Users/username/.docker/machine/machines/default"
}```

Boot2docker is deprecated, but the concept stays the same. So your issue is the same for docker-machine and boot2docker as well. Actually, the boot2docker .iso image is currently used internally by docker-machine :-)

**Comment by mhgrove** [comment] 2016-01-29 17:22
I did that, but to no avail.

I get the feeling that the difference is that you're referring to `http` as the scheme for the local docker machine url, and mine is telling me `tcp`.

**Comment by gesellix** [comment] 2016-01-29 17:25
yes. Maybe you even need to use `https`. I don't know of the internals and whether they gracefully handle a wrong url schema.

**Comment by mhgrove** [comment] 2016-01-29 17:26
ok. so now i guess the question is why is docker-machine using `tcp` and not `http(s)` =)

**Comment by gesellix** [comment] 2016-01-29 17:29
Docker itself always uses `tcp`. Due to Java specifics (URLConnection implementations and their discovery), a `http(s)` url might be preferred as config parameter.

**Comment by bmuschko** [comment] 2016-02-02 12:32
You can just go with `https` in the configuration of `docker.url` and set the `certPath`. @gesellix provided an example above. That should do it.

**Comment by mhgrove** [comment] 2016-02-02 15:09
I tried that and it didnt work, i keep getting the broken pipe issue.  it looks like i'm getting a binary response no matter what and dockerjava is obviously expecting http

**Comment by gesellix** [comment] 2016-02-02 15:41
I suggest to enable the debug logs. It would be nice to know whether docker-java gets the correct certPath. As car as I can tell fro the stack trace it should be a TLS Konfiguration issue.

**Comment by geoHeil** [comment] 2016-02-17 16:39
I get the same error using the latest docker toolbox. However I have 2 projecs: 

1. NOT using the java application plugin  but no errors e.g. image is created successfully
2. using the java application plugin - this one has the described error. But the correct paths are set:

    ```
if (System.env.DOCKER_HOST) {
        url = "$System.env.DOCKER_HOST".replace("tcp", "http")
        if (System.env.DOCKER_CERT_PATH) {
            certPath = new File("$System.env.DOCKER_CERT_PATH")
        }
    } else {
        url = 'unix:///var/run/docker.sock'
    }
```

**Comment by cdancy** [comment] 2016-02-17 21:11
@mhgrove is this still an issue for you? You might try looking at #154 for advice on how to move forward.

**Comment by mhgrove** [comment] 2016-02-18 11:37
Yeah, it's still an issue.  I read 154, but it seems unrelated; everything afaict, builds fine. My naive interpretation of what's going on would lead me to agree with @gesellix  that its a TLS configuration issue.  But I don't know how to update the configuration.

I still need to enable debugging to get more detailed logs in the hope that helps us figure out exactly what's going on.

**Comment by gesellix** [comment] 2016-02-18 12:23
I guess @cdancy meant #160 instead of #154?

@mhgrove what about trying to explicitly choose an "known invalid path" like `/tmp`? If for such invalid configuration the same error appears, we could be more content (not guarantee) that the issue is around certPath or the certificate files.

**Comment by geoHeil** [comment] 2016-02-18 13:01
I "fixed" this issue by creating a completely new project and using and then copying each step back to the initial project.

```
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}"
        classpath "io.spring.gradle:dependency-management-plugin:0.5.5.RELEASE"
        classpath 'com.bmuschko:gradle-docker-plugin:2.6.5'
    }
}

plugins {
    id "org.asciidoctor.convert" version "1.5.3"
}

apply plugin: 'java'

sourceCompatibility = 1.8
targetCompatibility = 1.8

apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'spring-boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'application'
apply plugin: 'com.bmuschko.docker-java-application'
apply plugin: 'org.asciidoctor.convert'
apply plugin: 'war'
```

and 

`dockerDistTar.environmentVariable('SPRING_PROFILES_ACTIVE', "local")`

**Comment by bmuschko** [comment] 2016-02-21 13:49
@mhgrove If you want additional help on this issue please provide a minimalistic sample project on GitHub that reproduces the issue. Otherwise it's too hard to identify the root cause. If we don't hear back from you in the next two weeks, we'll close the issue.

**Comment by bmuschko** [comment] 2016-02-28 15:18
@mhgrove I think you have some sort of configuration issue with your Docker instance. Without a specific setup we can try out it's hard to help you. BTW: We now provide a [Vagrant box](https://github.com/bmuschko/gradle-docker-plugin/blob/master/vagrant/Vagrantfile) that you can use instead of Boot2Docker that already has the proper setup.

**Closed by bmuschko** 2016-02-28 15:18 UTC

**Comment by rahulakash** [comment] 2017-04-14 21:53
I resolved this issue by installing [Docker For Mac](https://docs.docker.com/docker-for-mac/install/)  instead of the Docker Toolbox (Kitematic).
