### ISSUE TITLE
Can't Build Image on JDK 13 environment and gradle version 6.0

### ISSUE THREAD

**Issue by Moshiour027** [bmuschko/gradle-docker-plugin#885] opened 2019-11-12 07:02 UTC
Task buildImage fails on JDK version 13,
Error Message: 
 Cannot find method "setCreated" in java.net.Socket. Unsupported JVM?

### Expected Behavior
buildImage task just runs fine in JDK 12 and Gradle version. 6.0 but the issue occurs when we run in JDK 13.

### Your Environment
JDK 13, Gradle Version 6.0

**Comment by bmuschko** [comment] 2019-11-12 14:17
This is effectively a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/874. See my comment here: https://github.com/bmuschko/gradle-docker-plugin/issues/874#issuecomment-542425209.

**Closed by bmuschko** 2019-11-12 14:17 UTC

**Comment by joerg-pfruender** [comment] 2020-02-17 09:20
I cloned your repository and I've build the plugin with upgrading the com.github.docker-java:docker-java dependency to 
```shaded("com.github.docker-java:docker-java:3.2.0-rc2")```
and everything worked.

Please upgrade to `com.github.docker-java:docker-java:3.2.0` as soon as it is released.

**Comment by bmuschko** [comment] 2020-03-11 01:20
FYI: I just released a version of the plugin, 6.2.0, with the latest Docker Java version as dependency. It should be Java 13-compatible AFAIK. Could you please give it a try?

**Comment by joerg-pfruender** [comment] 2020-03-11 11:31
@bmuschko Works like a charm! Thank you very much!

**Comment by bmuschko** [comment] 2020-03-11 13:24
@joerg-pfruender Awesome, thanks for the feedback.
