### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket on X86_64 CPU Linux

### ISSUE THREAD

**Issue by AlexDumanskiy** [bmuschko/gradle-docker-plugin#1153] opened 2023-01-20 14:10 UTC
Getting an 
"Exception in thread "docker-java-stream-784262759" java.lang.NoClassDefFoundError: Could not initialize class com.bmuschko.gradle.docker.shaded.com.github.dockerjava.transport.DomainSocket"
while running dockerBuildImage task.

Looks very similar to this issue: https://github.com/bmuschko/gradle-docker-plugin/issues/1035
But I do not use an ARM processor.

### Expected Behavior
Task communicating with docker daemon to build an image.

### Current Behavior
The exception above appears, gradle hangs for a long time doing (probably) nothing.

### Context
I am trying to switch to com.bmuschko.docker-spring-boot-application plugin for building images for our application.
The application is old and known to work, the images were build using a shitty custom gradle build script before.

### Steps to Reproduce (for bugs)

Steps to reproduce (on Linux):
1. Clone the repo:
https://github.com/AlexDumanskiy/reproducableException
2. Run the task
./gradlew dockerBuildImage

### Your Environment

CPU is Intel(R) Xeon(R) E-2176M (x86_64, not an ARM/M1-2)
Gradle 7.6
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
Linux 6.0.6 x86_64 SMP PREEMPT_DYNAMIC

**Comment by AlexDumanskiy** [comment] 2023-01-20 14:11
I tries workaround mentioned here: https://github.com/bmuschko/gradle-docker-plugin/issues/1035#issuecomment-1217459991
With both 3.12.3 and 3.12.4 versions with no result.

Will be happy to provide any additional info needed.
Will also try on a different Linux distro and CPU.

**Comment by AlexDumanskiy** [comment] 2023-01-20 15:49
Interesting observation:

The exception above shows on the second and consequent runs.
On the first run there is another exception:
`Exception in thread "docker-java-stream--832346849" java.lang.UnsatisfiedLinkError: 'java.lang.String com.bmuschko.gradle.docker.shaded.com.sun.jna.Native.getNativeVersion()'
`

**Comment by AlexDumanskiy** [comment] 2023-01-20 16:30
Works whith the following jdk:

openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

**Comment by michaelrobertharmon** [comment] 2023-01-20 19:36
I've observed the same error as @AlexDumanskiy reported with the following JDK and plugin revision 9.1.0

 └> $ java -version
openjdk version "11.0.17" 2022-10-18
OpenJDK Runtime Environment Temurin-11.0.17+8 (build 11.0.17+8)
OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

I reverted to plugin revision 9.0.0 which doesn't demonstrate the error.

**Comment by bmuschko** [comment] 2023-01-20 23:24
@AlexDumanskiy Setting a different Docker Java version won't work as the library has been shaded with the current version.

**Comment by bmuschko** [comment] 2023-01-20 23:25
Your issue is a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/1147. I am going to close it. Thanks for providing the sample project to reproduce. I am planning to turn it into a test case.

**Closed by bmuschko** 2023-01-20 23:26 UTC

**Comment by bmuschko** [comment] 2023-01-20 23:40
Hhhmm, at least on MacOS I cannot reproduce the issue. We have functional tests running CI with Ubuntu that are very similar but don't seem to have the issue.

**Comment by AlexDumanskiy** [comment] 2023-01-21 10:28
@bmuschko, I opened a separate ticket because I thought that being run on Linux or Mac might have different root causes, since JNA is involved.
I will try Ubuntu and add my results to #1147
