### ISSUE TITLE
Make AbstractDockerRemoteApiTask variables optional

### ISSUE THREAD

**Issue by cdancy** [bmuschko/gradle-docker-plugin#192] opened 2016-04-03 01:41 UTC
`classpath` and `url` variables of `AbstractDockerRemoteApiTask` should be optional. These should be specified in the DockerExtension and only if one wants to override them should they have the option of doing so through the task.

**Comment by bmuschko** [comment] 2016-04-03 12:31
These two properties are required as input properties for the task action to run properly. While there might be default values that come from the extension, a user can still overwrite them on the task level.

    task dockerBuild(type: DockerBuildImage) {
        url = null
    }

For that reason they cannot be optional. Optional here means that a value has to be assigned. The property cannot be null. BTW: What's the driver for wanting to make the optional?

**Comment by cdancy** [comment] 2016-04-03 13:01
@bmuschko I already have a PR going for this which resolves this problem. I've found in a particular setup where I'm doing an `apply from: ..some file location` its complaining about the `classpath` not being set. The logic I went with is what you just hinted at:

    1.) DockerExtension holds the default.
    2.) Anything defined on the task itself overrides the default.

Not to mention for anyone looking at the code it gives one the impression that a classpath needs to be defined for a given task when this is not the case. Instead I created a `classpath` variable in  `DockerExtension` which will hold the generated classpath we create at runtime, and should the user want to override this, they can do so by setting another classpath on the task itself.

**Comment by bmuschko** [comment] 2016-04-03 13:13
> I've found in a particular setup where I'm doing an apply from: ..some file location its complaining about the classpath not being set.

Wasn't this the discussion where people didn't know about the limitations in Gradle that the plugin has to be applied by type and not by identifier? This needs to be fixed in Gradle core. It's rather a side-effect than the cause.

> Not to mention for anyone looking at the code it gives one the impression that a classpath needs to be defined for a given task when this is not the case.

Well, the property needs to be defined for the task but a default is provided by extension. It also needs to have input annotations for up-to-date checks e.g. when you change the Docker Java version you will likely get a different classpath. That's also why it shouldn't be marked optional.

**Comment by bmuschko** [comment] 2016-04-03 13:16
Also, one more thing I'd like to mention is the fact that we should probably decouple the extension from the plugin. We should probably have a base plugin that should provides the tasks and nothing else. The extension is just synthetic sugar really. By removing the properties you block the path to making it happen.

**Comment by cdancy** [comment] 2016-04-03 17:55
@bmuschko take a look at #194 and tell me what you think. I understand your criticism above but check out what I've done and see if they're still warranted.

**Closed** 2016-04-11 02:09 UTC
Labels: enhancement
