### ISSUE TITLE
Push to insecure docker registry

### ISSUE THREAD

**Issue by avarabyeu** [bmuschko/gradle-docker-plugin#258] opened 2016-08-11 17:09 UTC
Hello. Trying to push my image to insecure docker registry via https. Here is configuration:

```
 docker {
    url = "http://someServer.com:2375"
    registryCredentials {
        url = 'https://someServer.com:5000'
    }
}

task pushDockerImage(type: DockerPushImage) {
     imageName="${dockerRegistryUrl}/${project.name}:${version}".toLowerCase()
}
```

Basically, i need to provide certificate somewhere or just disable security check (as i did for command line by adding --insecure-registry option). 
Can someone help? Is that possible to push image to insecure registry?

**Comment by orzeh** [comment] 2016-08-11 19:36
Does your registry requires authentication? If not, you can simply remove `registryCredentials` configuration and it should work out of the box if docker daemon is configured with `--insecure-registry` option (it's true as you said).

If authentication is required you must provide credentials is `registryCredentials`.

From your build script snippet I can see that your image name does not match Dockers convention: __[REGISTRY]/[REPOSITORY]/[IMAGE]:[TAG]__, so your `pushDockerImageTask` should be:
  
````groovy
task pushDockerImage(type: DockerPushImage) {
     imageName="${dockerRegistryUrl}/${project.group}/${project.name}:${version}".toLowerCase()
}
````
I've used `project.group` as repository, but obviously you can change it to whatever you want.

**Comment by avarabyeu** [comment] 2016-08-12 08:18
The problem is that i build project from host which does not contain docker engine, so i'm unable to configure --insecure-registry in this case. I thought, push to registry works via remote api, so configuring docker daemon doesn't make sense, isn't it?

**Comment by eshepelyuk** [comment] 2016-08-12 08:21
Well, if the host where you build the project doesn't run `Docker Engine` - it means - you somehow configure your build script to use remote `Docker Engine`.
So that remote engine should have `--insecure registry` configured

**Comment by orzeh** [comment] 2016-08-17 09:35
I'm closing it. I think the problem is related to Docker Engine configuration not the plugin itself.

**Closed by orzeh** 2016-08-17 09:35 UTC
Labels: question
