### ISSUE TITLE
Convert task inputs to new Gradle Provider API

### ISSUE THREAD

**Issue by JLLeitschuh** [bmuschko/gradle-docker-plugin#654] opened 2018-09-05 21:28 UTC
https://docs.gradle.org/current/userguide/lazy_configuration.html

### Expected Behavior
All fields on all tasks need to support being configured lazily.

### Current Behavior
Currently, only some of the fields are settable lazily. For example, `DockerTagImage::repository` is missing a lazy configuration API.

### Context
The current way of setting fields that come from other fields is a very convoluted mix of `afterEvaluate` inside of task configurations.
For example:
```kotlin
val tagForCompany =
    tasks.register("dockerTagForCompanyUpload", DockerTagImage::class.java) {
        afterEvaluate {
            repository = "$companyDockerRepositoryUrl/${buildImage.tag.stripVersion()}"
            imageId = buildImage.tag
            tag = version.toString()
        }
        dependsOn(buildImage)
    }

tasks.register("dockerPushCompanyImage", DockerPushImage::class.java) {
    registryCredentials = docker.registryCredentials
    afterEvaluate {
        imageName = "$companyDockerRepositoryUrl/${tagForPlexxi.get().imageId.stripVersion()}"
    }
    tag = version.toString()

    dependsOn(tagForCompany)
}
```

### Your Environment
Gradle 4.9.
Plugin version 3.6.1

**Comment by bmuschko** [comment] 2018-09-05 21:29
Thanks for bringing this up. Closing as a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/561. I am currently working on a first step toward it.

**Closed by bmuschko** 2018-09-05 21:29 UTC
