### ISSUE TITLE
How to add an archive file to the Docker image?

### ISSUE THREAD

**Issue by asarkar** [bmuschko/gradle-docker-plugin#972] opened 2020-09-24 06:06 UTC
I'm using the Spring Boot application plugin and would like to add an external archive file to the Docker image, and then extract it. This would be in addition to the application JAR file already being added.

So far, I've done the following:

```
val healthProbe: Configuration by configurations.creating
dependencies {
    healthProbe("com.mycompany:health-probe:1.0.0-SNAPSHOT@tgz")
}
val copyHealthProbe = tasks.create<Copy>("copyHealthProbe") {
    from(healthProbe)
    into(file("$buildDir/docker/distributions"))
    rename { "health-probe.tgz" }
}

tasks.dockerSyncBuildContext {
    finalizedBy(copyHealthProbe)
}

tasks.withType<com.bmuschko.gradle.docker.tasks.image.Dockerfile> {
    addFile("distributions/health-probe.tgz", "/")
}
```

But this fails with the following exception:
```
Error during callback
java.lang.RuntimeException: java.io.IOException: native write() failed : Broken pipe
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:153)
```

The generated `Dockerfile` can be used to successfully build an image from the command line.
```
java --version
openjdk 11.0.7 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```

Gradle 6.6.1.

**Comment by asarkar** [comment] 2020-09-25 09:10
After more investigation, it seems to be an issue on Mac only. I see this in the Docker for Mac logs:
```
error forwarding client's request to Docker: write unix ->/Users/me/Library/Containers/com.docker.docker/Data/docker.raw.sock: write: broken pipe
```
There are many reports of "broken pipe" in various projects, none helpful.

**Comment by Mazorius** [comment] 2020-10-27 15:50
I have the same issue with `id("com.bmuschko.docker-spring-boot-application") version "6.6.1"`.

``` gradle
...
docker {
  springBootApplication {
    baseImage.set("adoptopenjdk/openjdk8:alpine-jre")
    ports.set(listOf(8080))
    maintainer.set("...")
    mainClassName.set(springBoot.mainClassName)
    images.set(
      setOf(
        "${rootProject.name}:${project.version}",
        "${rootProject.name}:latest"
      )
    )
    jvmArgs.set(listOf("-Dspring.profiles.active=production", "-Xmx2048m"))
  }
}
```

# Output

``` console
> Task :dockerBuildImage
Building image using context '/projectPath/build/docker'.
Using images 'projectName:3.0.0', 'projectName:latest'.

Error during callback
java.lang.RuntimeException: java.io.IOException: native write() failed : Broken pipe
at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:153)
at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:8)
at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: native write() failed : Broken pipe
at com.github.dockerjava.httpclient5.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:319)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:150)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:125)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:204)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.io.entity.InputStreamEntity.writeTo(InputStreamEntity.java:96)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RequestEntityProxy.writeTo(RequestEntityProxy.java:106)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:153)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:148)
at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:225)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:220)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:165)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:149)
... 4 more
    Suppressed: java.io.IOException: native write() failed : Broken pipe
at com.github.dockerjava.httpclient5.UnixDomainSocket$UnixSocketOutputStream.write(UnixDomainSocket.java:319)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:126)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.ChunkedOutputStream.close(ChunkedOutputStream.java:228)
at com.bmuschko.gradle.docker.shaded.org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:154)
... 29 more
```

**Comment by bmuschko** [comment] 2020-11-07 04:30
From the stack trace, it looks like an issue in the Docker Java library. Seems like you already reported it over there but it has been closed. Not sure how to help with the issue.

@Mazorius Are you saying that an archive file is not involved in your project?

**Comment by asarkar** [comment] 2020-11-07 05:07
@bmuschko the docker-java ticket was closed by stale bot, not because they fixed it.

**Comment by bmuschko** [comment] 2020-11-09 01:01
@asarkar I didn't intend to imply that the issue is fixed. I just saw that it was closed. Still, I believe it probably needs to fixed in Docker Java.

**Comment by Mazorius** [comment] 2020-11-09 09:49
Thanks @bmuschko for your answer and for the plugin ;-)

I will create a sample and give you the link.

**Comment by asarkar** [comment] 2021-02-06 04:58
@Mazorius Just checking if you found time to create the sample.

**Comment by bmuschko** [comment] 2021-06-09 23:42
Looks like this issue didn't get any traction from the community. Please continue the discussion if you want to move forward with a fix.

**Closed by bmuschko** 2021-06-09 23:42 UTC
Labels: docker-java, question

**Comment by asarkar** [comment] 2021-06-11 07:02
I'm not sure how to continue the discussion that'd drive a successful resolution. docker-java doesn't seem to be give a crap about bugs; the ticket I had opened was closed when it got stale.

**Comment by bmuschko** [comment] 2021-06-11 14:08
To get this done I think someone would need to identify and underlying issue and send a PR to Docker Java. I won't have the time to work on it but if you want to tackle it from your end, we could then do the work to integrate or fix anything needed in the plugin. Sorry, that you didn't get a response from them. I left a comment in the issue.

**Comment by asarkar** [comment] 2021-06-14 22:37
> I think someone would need to identify and underlying issue and send a PR to Docker Java

Usually that’s the approach I’d take, but given that fact that docker-java hasn’t responded to or acknowledged the bug I created, I’m not going to do anything for them. It seems their approach is “we have created a library and done the world a favor, take it or leave it”. I’m not going to promote that approach.

**Comment by bmuschko** [comment] 2021-06-15 02:23
I personally think it's more likely the fact that they are short on time or don't think that the issue is the most important one so they didn't prioritize. I do have the same issue and am relying on the community to contribute as much as I can.
