### ISSUE TITLE
DockerStartContainer problem

### ISSUE THREAD

**Issue by PerMildner** [bmuschko/gradle-docker-plugin#858] opened 2019-09-19 14:12 UTC
I am trying to follow the example in the [user guide](https://bmuschko.github.io/gradle-docker-plugin/#executing_functional_tests_against_a_running_container) to emulate docker build + docker run (as suggested in #857) but the Dockerfile `ENTRYPOINT` is not run, and there is no indication that anything is wrong.
### Expected Behavior
I expect the container to run.
### Current Behavior
The container does not run. And there is no indication that anything went wrong.

### Your Environment
macOS 10.14.6, Docker version 19.03.2, build 6a30dfc.

### Steps to Reproduce (for bugs)

The following transcript shows that `docker build` + `docker run` behaves as expected, but the corresponding Gradle tasks just quietly does not run the container entry point.

My files:

```
-bash$ find . '(' -name gradle -prune -or -not -path '*/\.*' -not -name gradlew -not -name gradlew.bat -type f -exec printf '###### START %s:\n' '{}' \; -exec cat '{}' \; -exec printf '###### END %s\n\n' '{}' \; ')'
###### START ./Dockerfile:
FROM alpine:latest
ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]

###### END ./Dockerfile

###### START ./build.gradle:
import com.bmuschko.gradle.docker.tasks.container.DockerCreateContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStartContainer
import com.bmuschko.gradle.docker.tasks.container.DockerStopContainer
import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage

plugins {
    id 'base'
    id 'com.bmuschko.docker-remote-api' version '4.10.0'
}

task buildTestImage(type: DockerBuildImage) {
    inputDir.set(file("$projectDir"))
    dockerFile.set(file("Dockerfile"))

    tags.add('my-unit-tests:latest')
}

task createTestContainer(type: DockerCreateContainer) {
    dependsOn buildTestImage
    targetImageId buildTestImage.getImageId()
    
    autoRemove.set(true)

    volumes.add("$buildDir:/tmp/my_test_output")
}

task startTestContainer(type: DockerStartContainer) {
    dependsOn createTestContainer
    targetContainerId createTestContainer.getContainerId()
}

task stopTestContainer(type: DockerStopContainer) {
    dependsOn createTestContainer
    targetContainerId createTestContainer.getContainerId()
}

task myTest {
    dependsOn startTestContainer
    finalizedBy stopTestContainer
}


###### END ./build.gradle

###### START ./settings.gradle:
rootProject.name = 'docker-test'
###### END ./settings.gradle
```

Using `docker build` + `docker run` manages to run the `ENTRYPOINT` and pass the exit code back to the host:
```
-bash$ rm -rf build && docker build -t my-unit-tests-manual:latest . && docker run --rm -v $PWD/build:/tmp/my_test_outputs my-unit-tests-manual; echo "Docker run exited with $?"; echo 'The contents of ./build/ is:'; ls -l ./build/
Sending build context to Docker daemon  149.5kB
Step 1/2 : FROM alpine:latest
 ---> 961769676411
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
 ---> Running in ebdb926e289b
Removing intermediate container ebdb926e289b
 ---> c56474213903
Successfully built c56474213903
Successfully tagged my-unit-tests-manual:latest
The ENTRYPOINT is faking a test-error
total 4
-rw-r--r--    1 root     root            13 Sep 19 13:51 test_outputs.txt
Docker run exited with 37
The contents of ./build/ is:
total 8
-rw-r--r--  1 perm  staff  13 Sep 19 15:51 test_outputs.txt
```

Trying to do the same things with gradle, following the example in the [user guide](https://bmuschko.github.io/gradle-docker-plugin/#executing_functional_tests_against_a_running_container), quietly does not run the container `ENTRYPOINT`:

```
-bash$ rm -rf build && ./gradlew myTest; echo "Gradle exited with $?"; echo 'The contents of ./build/ is:'; ls -la ./build/.docker/

> Task :buildTestImage
Building image using context '/Users/perm/docker-test'.
Using Dockerfile '/Users/perm/docker-test/Dockerfile'
Using tags 'my-unit-tests:latest' for image.
Step 1/2 : FROM alpine:latest
 ---> 961769676411
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
 ---> Using cache
 ---> c56474213903
Successfully built c56474213903
Successfully tagged my-unit-tests:latest
Created image with ID 'c56474213903'.

> Task :createTestContainer
Created container with ID 'c1e9476bc7aa12cc63704c5eb88cf7964ea35cfa02968b627b2ce96747e6693b'.

> Task :startTestContainer
Starting container with ID 'c1e9476bc7aa12cc63704c5eb88cf7964ea35cfa02968b627b2ce96747e6693b'.

> Task :stopTestContainer
Stopping container with ID 'c1e9476bc7aa12cc63704c5eb88cf7964ea35cfa02968b627b2ce96747e6693b'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed
Gradle exited with 0
The contents of ./build/ is:
total 8
drwxr-xr-x  3 perm  staff  96 Sep 19 15:52 .
drwxr-xr-x  3 perm  staff  96 Sep 19 15:52 ..
-rw-r--r--  1 perm  staff  12 Sep 19 15:52 buildTestImage-imageId.txt
-bash$ 
```

**Comment by PerMildner** [comment] 2019-09-19 14:13
The Gradle project: [docker-test.zip](https://github.com/bmuschko/gradle-docker-plugin/files/3631666/docker-test.zip)

**Comment by PerMildner** [comment] 2019-09-19 20:44
I tried this on Ubuntu 18.04 and it tried to report some error the first time I ran it, but subsequent times it does like on macOS, quietly doing the wrong thing.

```
$ sudo rm -rf build && ./gradlew myTest; echo "Gradle exited with $?"; echo 'The contents of ./build/ is:'; ls -la ./build/.docker/

> Task :buildTestImage
Building image using context '/home/cera/docker-test'.
Using Dockerfile '/home/cera/docker-test/Dockerfile'
Using tags 'my-unit-tests:latest' for image.
Step 1/2 : FROM alpine:latest
 ---> 961769676411
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
 ---> Using cache
 ---> d41731ac75f1
Successfully built d41731ac75f1
Successfully tagged my-unit-tests:latest
Created image with ID 'd41731ac75f1'.

> Task :createTestContainer
Created container with ID '548029279e5717f76a3ff01ea1eff477e0bb83567b8adadb51ea3227135d7952'.

> Task :startTestContainer
Starting container with ID '548029279e5717f76a3ff01ea1eff477e0bb83567b8adadb51ea3227135d7952'.

> Task :myTest

> Task :stopTestContainer FAILED
Stopping container with ID '548029279e5717f76a3ff01ea1eff477e0bb83567b8adadb51ea3227135d7952'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stopTestContainer'.
> com.github.dockerjava.api.exception.NotModifiedException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 2s
4 actionable tasks: 4 executed
Gradle exited with 1
The contents of ./build/ is:
total 12
drwxrwxr-x 2 cera cera 4096 Sep 19 13:39 .
drwxrwxr-x 3 cera cera 4096 Sep 19 13:39 ..
-rw-rw-r-- 1 cera cera   12 Sep 19 13:39 buildTestImage-imageId.txt
XXX$ sudo rm -rf build && ./gradlew myTest; echo "Gradle exited with $?"; echo 'The contents of ./build/ is:'; ls -la ./build/.docker/

> Task :buildTestImage
Building image using context '/home/cera/docker-test'.
Using Dockerfile '/home/cera/docker-test/Dockerfile'
Using tags 'my-unit-tests:latest' for image.
Step 1/2 : FROM alpine:latest
 ---> 961769676411
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
 ---> Using cache
 ---> d41731ac75f1
Successfully built d41731ac75f1
Successfully tagged my-unit-tests:latest
Created image with ID 'd41731ac75f1'.

> Task :createTestContainer
Created container with ID '3f78a88e92431940987c335f55764876b7000e9541719c4696d4f7193c57ec96'.

> Task :startTestContainer
Starting container with ID '3f78a88e92431940987c335f55764876b7000e9541719c4696d4f7193c57ec96'.

> Task :myTest

> Task :stopTestContainer
Stopping container with ID '3f78a88e92431940987c335f55764876b7000e9541719c4696d4f7193c57ec96'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed
Gradle exited with 0
The contents of ./build/ is:
total 12
drwxrwxr-x 2 cera cera 4096 Sep 19 13:41 .
drwxrwxr-x 3 cera cera 4096 Sep 19 13:41 ..
-rw-rw-r-- 1 cera cera   12 Sep 19 13:41 buildTestImage-imageId.txt
XXX$ 
```

**Comment by cdancy** [comment] 2019-09-19 20:51
The `NotModifiedException` generally means the container/image already exist.

Have you tried things by hand yet and have done each step incrementally? Have you done the same with the gradle build? It's generally a good idea, at least with this plugin, to do things incrementally to confirm you get the expected output.

**Comment by cdancy** [comment] 2019-09-19 20:55
Looking at things I'm not even sure what you're expecting to happen? Everything that you've wired up appears to be working in exactly the way you noted. What is it that you want to do see happen?

**Comment by PerMildner** [comment] 2019-09-20 09:22
Thanks for looking at this.

@cdancy "What is it that you want to do see happen?" I want the gradle invocation to do the same thing as the command line `docker build ...` + `docker run ...` that I showed in the first transcript.

"What do I expect to happen?" I expected the gradle task `startTestContainer` to start the container, which would lead to the `ENTRYPOINT` command being run, but the `ENTRYPOINT` does not seem to run (since the script output does not appear on the console, and the expected file `test_outputs.txt` is not created in the mounted folder).

(I am new to Docker, Gradle, and this plugin, so it is quite likely that I have missed something obvious.)

**Comment by orzeh** [comment] 2019-09-20 09:37
@PerMildner you have a typo :) in Gradle script you have `volumes.add("$buildDir:/tmp/my_test_output")` but in ENTRYPOINT you have `/tmp/my_test_outputs/test_outputs.txt;` note additional **s** in folder name.

Regarding build error: your container simply exits before `stopTestContainer` is executed - that's why you get NotModifiedException intermittently.  In general you should create `DockerStopContainer` task if you have long running container like DB, HTTP server etc.

Also please note that you won't see console output from container, unless you use [DockerLogsContainer](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/container/DockerLogsContainer.html) task.

**Comment by PerMildner** [comment] 2019-09-20 10:54
@orzeh PEBKAC as usual:-) thanks. I also did `ls` on the wrong folder. Unfortunately, fixing this did not help. The volume mount does not seem to be available in the container (`/tmp/` is empty in the container):

I corrected the folder name in `volumes` argument, removed the `autoRemove` (so I can do `docker logs` later), and added a `ls -l /tmp` in the `Dockerfile` so I can see whether the mounted folder (`/tmp/my_test_outputs/`) is available in the container, but it is not:
```
bash$ rm -rf build && ./gradlew myTest; echo "Gradle exited with $?"; echo 'The contents of ./build/ is:'; ls -la ./build/

> Task :buildTestImage
Building image using context '/Users/perm/docker-test-2019-09-20'.
Using Dockerfile '/Users/perm/docker-test-2019-09-20/Dockerfile'
Using tags 'my-unit-tests:latest' for image.
Step 1/2 : FROM alpine:latest
 ---> 961769676411
Step 2/2 : ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error exit' ; echo 'The contents of /tmp:'; ls -la /tmp; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
 ---> Using cache
 ---> 41e68489dce3
Successfully built 41e68489dce3
Successfully tagged my-unit-tests:latest
Created image with ID '41e68489dce3'.

> Task :createTestContainer
Created container with ID '0b23f9abb35aea5cf0a1b733f69a8cea8ebeb2e0a07989e13a81ebd425d3f338'.

> Task :startTestContainer
Starting container with ID '0b23f9abb35aea5cf0a1b733f69a8cea8ebeb2e0a07989e13a81ebd425d3f338'.

> Task :myTest

> Task :stopTestContainer
Stopping container with ID '0b23f9abb35aea5cf0a1b733f69a8cea8ebeb2e0a07989e13a81ebd425d3f338'.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
4 actionable tasks: 4 executed
Gradle exited with 0
The contents of ./build/ is:
total 0
drwxr-xr-x   3 perm  staff   96 Sep 20 12:42 .
drwxr-xr-x  12 perm  staff  384 Sep 20 12:42 ..
drwxr-xr-x   3 perm  staff   96 Sep 20 12:42 .docker
bash$ docker logs '0b23f9abb35aea5cf0a1b733f69a8cea8ebeb2e0a07989e13a81ebd425d3f338'
The ENTRYPOINT is faking a test-error exit
The contents of /tmp:
/bin/sh: can't create /tmp/my_test_outputs/test_outputs.txt: nonexistent directory
total 8
drwxrwxrwt    2 root     root          4096 Aug 20 10:30 .
drwxr-xr-x    1 root     root          4096 Sep 20 10:42 ..
ls: /tmp/my_test_outputs/: No such file or directory
bash$ diff ../docker-test/build.gradle build.gradle 
22c22
<     autoRemove.set(true)
---
>     // autoRemove.set(true)
24c24
<     volumes.add("$buildDir:/tmp/my_test_output")
---
>     volumes.add("$buildDir:/tmp/my_test_outputs")
bash$ diff ../docker-test/Dockerfile Dockerfile
2c2
< ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
---
> ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error exit' ; echo 'The contents of /tmp:'; ls -la /tmp; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/; exit 37"]
bash$ 
```
Any ideas about what I am doing wrong with the volume mounting, or how I could troubleshoot it?
Also, I had expected the `exit 37` in the container to produce an error or exception in Gradle.

On `DockerStopContainer`: I followed the [user guide](https://bmuschko.github.io/gradle-docker-plugin/#executing_functional_tests_against_a_running_container) example. It uses both `autoRemove = true` _and_ `DockerStopContainer`. I'm just doing what I am told:-). Is it correct that `DockerStopContainer` is never meaningful together with `autoRemove = true`? (but, in that case, why do I not get the `NotModifiedException` _every_ time, surely the container should always be gone when `stopTestContainer` is run?

Similar for `DockerLogsContainer`, it too seem to require that the container persists after being run. In that case it too seems incompatible with `autoRemove = true`. Is that correct?

PS. `DockerCreateContainer.attachStdout` et al. sounds promising but they lack documentation. Do you know if they would make it possible to get the container stdout directed to the console?

The modified project, with the above changes: [docker-test 2019-09-20.zip](https://github.com/bmuschko/gradle-docker-plugin/files/3635477/docker-test.2019-09-20.zip).

**Comment by bhagyas** [comment] 2019-09-20 14:04
I can confirm this issue happening on my environment as well. 

This is using the latest docker-remote-api plugin version. 5.1.0. Docker version 19.03.2, build 6a30dfc

The plugin seems to be ignoring the Dockerfile ENTRYPOINT. Manually specifying entrypoint does not seem to help.

I am running a latest version of Docker, and I think it might have something to do with the Docker version.

**Comment by PerMildner** [comment] 2019-09-20 15:26
@bhagyas In my case the `ENTRYPOINT` is being run. The problem now is that the volumes are not mounted.

It was hard to see that the `ENTRYPOINT` was run since the plugin does not show the output from the `ENTRYPOINT` command, by default. I used `docker logs ...` (see transcript above) to verify that the `ENTRYPOINT` command is actually run.

**Comment by bhagyas** [comment] 2019-09-20 19:27
@PerMildner Do you think the entrypoint is being run before the volumes are mounted? I can also see the entrypoint being run, but there is no errors/output from the entrypoint command present.

**Comment by orzeh** [comment] 2019-09-25 21:35
@PerMildner everything works as expected. In `createTestContainer` task you define `volumes` but you probably want to setup `binds`. This might be confusing, see the [docs](https://docs.docker.com/storage/bind-mounts/).

This worked for me:
````groovy

task createTestContainer(type: DockerCreateContainer) {
    dependsOn buildTestImage
    targetImageId buildTestImage.getImageId()
    
    autoRemove.set(true)
    binds = ["$buildDir":"/tmp/my_test_outputs"]
}
````
Please note that file will be created in `build` directory.

I guess you can submit PR against our User Guide to cover everything you learned :smiley:

**Comment by PerMildner** [comment] 2019-09-26 09:52
@orzeh Thanks! Indeed I got confused by the fact that the `DockerCreateContainer` `volumes` property is unrelated to the `docker` `--volume` option. Also neither `volumes` nor `bind` is documented in the plugin [user guide](https://bmuschko.github.io/gradle-docker-plugin/), as far as I can tell.

However (here he goes again), although my original analysis was incorrect (the `ENTRYPOINT` _is_ run), two issues remains: 1. The non-zero exit code from the `ENTRYPOINT` is quietly ignored by `DockerStartContainer` instead of raising an exception, and 2. The non-existing source folder specified in the `volumes` of `DockerCreateContainer` is also ignored and does not cause any indication that something is wrong. Quietly ignoring erroneous input or error exits seems like a bad idea.

**Comment by orzeh** [comment] 2019-09-26 10:01
@PerMildner why do you assume that `DockerStartContainer` should throw exception when exit code is non-zero? I guess you can handle it by yourself using [onComplete](https://bmuschko.github.io/gradle-docker-plugin/#reacting_to_the_completion_of_an_operation) handler.

Regarding non-existing folder in volume, if Docker deamon doesn't complain why should we?

**Comment by PerMildner** [comment] 2019-09-26 11:44
"why do you assume that `DockerStartContainer` should throw exception when exit code is non-zero?"

Because it is what `docker run ...` does (which, was what I really wanted to emulate). However, you are right, the ([almost undocumented](https://docs.docker.com/engine/reference/commandline/start/)) `docker start ...` also does not report an error in this case, so this is OK.

"Regarding non-existing folder in volume, if Docker deamon doesn't complain why should we?"

Because this is what `docker start ...` does, see below. It seems reasonable to expect `DockerStartContainer` to behave similarly to `docker start`. I do now know what the Docker daemon does. The transcript below indicate that the daemon _does_ complain ("Error response from daemon: Mounts denied"), perhaps it is the [Docker Java library](https://github.com/docker-java/docker-java) that ignores the error. In either case the `docker` command line tool, not the daemon, is what normal users come in contact with, and in this case the `docker` command would give a helpful error.

```
bash$ docker build .
...
Successfully built f164d9a9d1ba
bash$ docker create f164d9a9d1ba
c870560e97861dcb1cc0b6eb10fb78e516742f7be8bac27f197acca62566218e
bash$ docker create -v '/this/folder/does/not/exist:/tmp/container_path' f164d9a9d1ba
48e1fb25b904948fea8652bb5a6f23b05b559abfce160aaa1a2aeffa72a3397b
bash$ docker start 48e1fb25b904948fea8652bb5a6f23b05b559abfce160aaa1a2aeffa72a3397b
Error response from daemon: Mounts denied: 
The path /this/folder/does/not/exist
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
Error: failed to start containers: 48e1fb25b904948fea8652bb5a6f23b05b559abfce160aaa1a2aeffa72a3397b
bash$ cat Dockerfile
FROM alpine:latest
ENTRYPOINT ["/bin/sh", "-c", "echo 'The ENTRYPOINT is faking a test-error' ; echo 'Test results' > /tmp/my_test_outputs/test_outputs.txt; ls -l /tmp/my_test_outputs/ >> /tmp/my_test_outputs/test_outputs.txt; exit 37"]

bash$ 
```

**Comment by bhagyas** [comment] 2019-09-26 11:48
I agree with what @PerMildner says. I ended up debugging the issue manually by using the docker command instead of using the Gradle plugin. 

The plugin should have provide debugging/diagnostic information whenever it encounters an issue at ENTRYPOINT.

**Comment by orzeh** [comment] 2019-09-26 12:02
@PerMildner can you check with path in which you can actually create file/dir? Because error message from deamon says "Mounts denied:" not that the path doesn't exist.

> In either case the docker command line tool, not the daemon, is what normal users come in contact with, and in this case the docker command would give a helpful error.

In the first line of README in this repo you can read that this plugin uses Docker REST API so it _might_ work differently than Docker CLI.

@bhagyas please rise a separate issue for your concerns. If you have an idea how this should work please submit a PR so that we can discuss and improve the plugin.

**Comment by PerMildner** [comment] 2019-09-26 12:14
If I change to `/tmp`, I get no error, is this the information you requested?

``docker create -v '/tmp:/tmp/container_path' f164d9a9d1ba
39503652a9c338436f2a7b07a6456495a912a18aae9366e6a96c9ac7524cee88
bash$ docker start 39503652a9c338436f2a7b07a6456495a912a18aae9366e6a96c9ac7524cee88
39503652a9c338436f2a7b07a6456495a912a18aae9366e6a96c9ac7524cee88
bash$
``

The Preview and formatting icons suddenly stopped working for me now, both with  Firefox and with Safari, so I cannot proof read my text.

**Comment by orzeh** [comment] 2019-09-26 12:17
@PerMildner try `/tmp/not_existing_folder`

> The Preview and formatting icons suddenly stopped working for me now, both with Firefox and with Safari, so I cannot proof read my text.

Same here :/

**Comment by PerMildner** [comment] 2019-09-26 12:33
Apparently GitHub has problems "GitHub is currently status yellow; this may affect site behavior and performance. Please check [GitHub Status](https://www.githubstatus.com/) for more information.".

So, lets "return to our regularly scheduled programming" of trying to resolve all my misunderstandings:-)

**Comment by bmuschko** [comment] 2019-09-28 21:54
@PerMildner Are you still experiencing problem? If not, let's close this issue.

**Comment by PerMildner** [comment] 2019-09-30 10:03
Yes, there are some remaining issues.

The main issue is that `DockerStartContainer` does not give an error when the `binds` parameter to the corresponding `DockerCreateContainer` cannot be used. As I showed above, it looks as if the Dockers daemon _does_ give an error in this case ("Error response from daemon: Mounts denied"). Quietly suppressing errors is a usability problem.

Similarly, the `volumes` parameter could give an error when the volume name looks like an absolute path (are Docker volume names allowed to contain the `/` directory separator?) (*).

The other issue is that the documentation for `DockerCreateContainer` does not make it sufficiently clear that the `volumes` property is unrelated to the `docker create` `--volume`  option. This is especially unfortunate since the `docker` command treats `--volumes` as more or less equivalent with its `--mount` option (but with different syntax). This is what caused me to initially use the wrong property with `DockerCreateContainer` (*).

Also, it does not help that the `docker create` option `--mount` corresponds to the `DockerCreateContainer` property  with the different name`binds`.

Looking again, `DockerCreateContainer` is completely undocumented, as far as I can tell. It is only present without comment (and without `volumes` or `mounts`) in an example in the [user manual](https://bmuschko.github.io/gradle-docker-plugin/). The [JavaDoc](https://bmuschko.github.io/gradle-docker-plugin/api/com/bmuschko/gradle/docker/tasks/container/DockerCreateContainer.html) also has no relevant documentation.

(*) Fixing either, or both, of these two issues would have helped me avoid the problems that caused me to create this ticket.

**Comment by bmuschko** [comment] 2019-09-30 13:02
@PerMildner It might be not be apparent but almost all of the communication work from this plugin to the Docker Daemon is performed by the Docker Java library. We are not actively suppressing any error message. If we do, then it's a bug in our plugin. The same goes for providing relevant input values. Most of the time, we are just calling off to the API of Docker Java with the same property names.

There are some differences between the behavior of the `docker` CLI and the Docker Daemon that we are aware of. If you feel that the `docker` CLI provide more convenient behavior or error messaging then there's nothing speaking against calling `docker` directly with an `Exec` command.

Documentation is always something we could improve on. I've been trying to add more documentation and Javadocs over the past months. It'll take a more concerted effort (also by contributors) to improve on it. Generally speaking, it would be very similar to the Javadocs in Docker Java classes e.g. [CreateContainerCmd.java](https://github.com/docker-java/docker-java/blob/master/docker-java-api/src/main/java/com/github/dockerjava/api/command/CreateContainerCmd.java). If you have a deeper look at the Javadocs of Docker Java, you will find they are also not perfect when it comes down to the docs.

Thanks for raising those issues again. They have come up in the past. IMHO they mostly boil down to better documentation, in the user guide and the Javadocs. I am hoping that we can get some additional help from the community to improve on it. Reminder from my end: This is an open source project and the main committers are spending their free-time on it.

**Comment by PerMildner** [comment] 2019-09-30 19:29
Yes, this is not the only project that needs a lot more documentation, but it certainly contains more documentation and functionality than I payed for.

I do not know whether the error is suppressed by this plugin, by Docker Java, or somewhere else. I do know that can take a lot of time to figure out what is wrong when code silently suppresses error conditions.

Now that I know the right way to call these classes I probably have no reason to use `Exec` task anymore.

I think I have said all that I can about this issue. I have found ways to work around the issues.

**Comment by cdancy** [comment] 2019-10-01 10:32
Closing for now as it seems your past things. And as Ben alluded to above: the docker `cli` wraps various REST calls to make things simpler for the end-user. This plugin acts as a one-to-one mapping of each of those REST calls to a given gradle task which means you have to build things out. For more complicated setups/scenarios you might want to think about creating a "site plugin" that wraps a lot of this functionality into a single task (that's what we do here).

**Closed by cdancy** 2019-10-01 10:32 UTC
Labels: question
