### ISSUE TITLE
Is it possible to get a credentials from local installed docker for push?

### ISSUE THREAD

**Issue by FirninFactoryPostProcessor** [bmuschko/gradle-docker-plugin#746] opened 2019-02-07 11:13 UTC
Hi, previously I used a Transmode gradle-docker plugin  (https://github.com/Transmode/gradle-docker) where it was possible to not configure credentials to private docker repo if I already logged in it on my local installed Docker. Your gradle-docker-plugin uses Docker remote API unlike Transmode one. Is it possible to add credentials directly from locally installed Docker(using this plugin) instead of using docker{registryCredentials{}} with setting username and password? I don't want to write the username and password in my build.gradle file.

My question could be ill-defined because my Docker knowledge is not so good, especially about its API.

**Comment by bmuschko** [comment] 2019-02-07 14:14
I believe Docker Java automatically uses the credentials you provided via `docker login` without the need to specify them via `docker.registryCredentials`. Is that your issue?

**Comment by FirninFactoryPostProcessor** [comment] 2019-02-07 15:36
I've got "> Could not push image: no basic auth credentials" without registryCredentials when I tried to run my gradle task(type: DockerPushImage) The only plugin I applied - 'com.bmuschko.docker-remote-api' (because I'm using it not for java app, but need JDK image). 

I could push an image to the private repo with registryCredentials or from another plugin(after docker login) but it doesn't work for me in this issue

**Comment by bmuschko** [comment] 2019-02-07 15:38
OK, thanks for the info. I will try it out soon and see if I can reproduce.

**Comment by FirninFactoryPostProcessor** [comment] 2019-02-13 08:39
Hi, may I ask - is there any new information about this issue?

**Comment by bmuschko** [comment] 2019-02-13 17:03
Didn't have a chance to look at it yet. Can you provide me with some sample code?

**Comment by FirninFactoryPostProcessor** [comment] 2019-02-14 11:29
`buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:4.4.0'
    }
}

apply plugin: 'com.bmuschko.docker-remote-api'
sourceCompatibility = JavaVersion.VERSION_11

import com.bmuschko.gradle.docker.tasks.image.DockerBuildImage
import com.bmuschko.gradle.docker.tasks.image.DockerPushImage
import com.bmuschko.gradle.docker.tasks.image.Dockerfile
import org.gradle.internal.os.OperatingSystem

task copyFolder(type: Copy) {
    from fileTree('.')
    into 'build/docker/copy-folder/'
}

task createDockerfile(type: Dockerfile) {
    dependsOn copyFolder
    from('url/adoptjdk11:latest')
    addFile "test", "/app"
    workingDir("/app")
    exposePort(80)
}

task buildImage(type: DockerBuildImage) {
    dependsOn createDockerfile
    tags = ["url/testimage:latest"]
    inputDir = file("build/docker")
}

docker {
    registryCredentials {
        url = 'url'
//        username = 'username'
//        password = 'password'
    }
}

task dockerPushImage(type: DockerPushImage) {
    imageName = "url/testimage"
}

dockerPushImage.dependsOn buildImage`

My build.gradle is the same with given example, but with some additional Gradle tasks before the "copyFolder" and real URL & credentials. I have remote docker repo with JDK image, I want to build my image based on JDK image(with files, copied by "copyFolder")  and push it into that remote repo. Remote JDK image could be used for 'FROM' in the dockerfile if I already provided credentials to the remote docker repo by "docker login" in my system, but there are troubles with pushing the image - "> Could not push image: no basic auth credentials". I have no idea how it could be possible when pulling the image from that repo is fine, but not pushing. It couldn't be a problem with push permissions in this credentials or something like that because I pushed this image with uncommented username and password or when I used another plugin.

**Comment by bmuschko** [comment] 2019-02-15 14:23
@cdancy @orzeh Any chance you have some time to look at it?

**Comment by cdancy** [comment] 2019-02-16 23:01
> I don't want to write the username and password in my build.gradle file.
@FirninFactoryPostProcessor so a common, and I would say proper, way to get around this is to either define the properties in your users gradle.properties file or as environment variables that you can read and inject. You should never be putting that sensitive stuff in your file directly but instead sourced from a hidden file or the environment.

**Comment by bmuschko** [comment] 2019-02-18 14:44
@cdancy I believe the original question was more around the fact that a user shouldn't have to provide credentials at all if you previously logged into the registry. This plugin should simply pick up those credentials for [Docker's credentials store](https://docs.docker.com/engine/reference/commandline/login/#credentials-store).

**Comment by dima-spire** [comment] 2019-02-21 02:33
> if you previously logged into the registry
Wouldn't that break repeatable builds? Let's say I logged in to a registry, so project builds for me. But my colleague didn't, and project doesn't build for them.

**Comment by FirninFactoryPostProcessor** [comment] 2019-02-21 13:04
@dima-spire 
A task with pushing image is not running on every build, it needs for CI, so credentials shouldn't be declared in the properties file or in a similar way.

**Comment by lakowske** [comment] 2019-04-11 20:28
We're also looking for this feature if it's not present already.  

We don't want to share registry credentials in our properties file or have it checked into a git repo, but rather expect that the user/agent has injected it into the environment (e.g. on the filesystem at a well know location: ~/.docker/config).  We'd consider non-repeatable builds due to a lack of credentials a feature.

**Comment by cdancy** [comment] 2019-04-11 20:37
@lakowske we've been talking about this, and workarounds, on #788 . Check that out and see if it provides any insight.

**Closed** 2019-10-29 23:18 UTC
Labels: enhancement

**Comment by ashwiniag** [comment] 2020-03-25 07:56
Hi, I was running build.gradle.kts in Jenkins (on ec2 with IAM role), faced similar issues. It has worked with following edits in `~/.docker/config` file:

Earlier: 
```
{
	"auths": {
		"xxxx.dkr.ecr.<region>.amazonaws.com": {
			"auth": "<alpha-numeric-token>"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.6 (linux)"
	}
}
```
Current:
```
{
	"auths": {
		"xxxxx.dkr.ecr.<region>.amazonaws.com": {}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.6 (linux)"
	}
}
```
I am assuming, gradle dint needed any auth-token since EC2 IAM role was taking care of uploading docker image in ECR.

**Comment by bmuschko** [comment] 2020-03-26 00:08
@ashwiniag This should work as-is. If it doesn't then it's likely a bug. Please open a new issue if you think we should should look into it. We'll definitely need the stack trace.
