### ISSUE TITLE
Unable to use gradle-docker-plugin in a file other than the main build file

### ISSUE THREAD

**Issue by dpancs** [bmuschko/gradle-docker-plugin#588] opened 2018-05-29 20:00 UTC
### Expected Behavior

I want to split a large build.gradle file into multiple files and I expect my docker tasks to work without issues.
### Current Behavior

I am getting a build failure 
```~/dev/sampleproj ᐅ ./gradlew createAppImage
> Task :createAppImage FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createAppImage'.
> Could not resolve all files for configuration ':dockerJava'.
   > Could not find com.aries:docker-java-shaded:3.0.14.
     Required by:
         project :
``` 
when I try to split my main build.gradle into build.gradle and gradle/docker.gradle as mentioned in the Readme.md

### Context

I want to split my build.gradle into multiple files to make it easy to handle different tasks.

### Steps to Reproduce (for bugs)

[sampleproj.zip](https://github.com/bmuschko/gradle-docker-plugin/files/2050539/sampleproj.zip)
1. Download the zip file and unzip it
2. Execute the task createAppImage

### Your Environment

Oracle JDK 1.8, Gradle v4.7.1, gradle-docker-plugin v3.2.7

**Comment by cdancy** [comment] 2018-05-29 20:06
@dpancs looks like it is having problems resolving the `docker-java-shaded` lib. Not sure if this is expected behavior or not given this setup but it does indeed feel wrong.

In either event try adding the below snippet to your "createAppImage" script just prior to applying the plugin and outside of the buildscript block and let me know if that helps:
```
    repositories {
        jcenter()
    }
``

**Comment by dpancs** [comment] 2018-05-29 20:52
I added the code snippet as mentioned and am getting a different error now:
```
Error during callback
com.github.dockerjava.shaded.org.apache.http.client.ClientProtocolException
        at com.github.dockerjava.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
        at com.github.dockerjava.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
        at com.github.dockerjava.shaded.org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:701)
        at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at com.github.dockerjava.shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at com.github.dockerjava.shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:697)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.github.dockerjava.shaded.org.apache.http.client.NonRepeatableRequestException: Cannot retry request with a non-repeatable request entity
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:107)
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at com.github.dockerjava.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        ... 18 more
Caused by: java.io.IOException: Broken pipe at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@2d0dd4ab; file=/Users/dpancholi/Library/Containers/com.docker.docker/Data/s60; connected=true; bound=false]
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXOutputStream.write(AFUNIXSocketImpl.java:260)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.SessionOutputBufferImpl.streamWrite(SessionOutputBufferImpl.java:124)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:136)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:167)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.SessionOutputBufferImpl.write(SessionOutputBufferImpl.java:179)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.SessionOutputBufferImpl.writeLine(SessionOutputBufferImpl.java:219)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.ChunkedOutputStream.flushCacheWithAppend(ChunkedOutputStream.java:123)
        at com.github.dockerjava.shaded.org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:179)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:229)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:299)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.ReaderWriter.writeTo(ReaderWriter.java:116)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeTo(AbstractMessageReaderWriterProvider.java:79)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:105)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.InputStreamProvider.writeTo(InputStreamProvider.java:60)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.jaxrs.filter.LoggingFilter.aroundWriteTo(LoggingFilter.java:300)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
        at com.github.dockerjava.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:517)
        at com.github.dockerjava.shaded.org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:499)
        at com.github.dockerjava.shaded.org.glassfish.jersey.apache.connector.ApacheConnector$2.writeTo(ApacheConnector.java:583)
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.RequestEntityProxy.writeTo(RequestEntityProxy.java:123)
        at com.github.dockerjava.shaded.org.apache.http.impl.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:156)
        at com.github.dockerjava.shaded.org.apache.http.impl.conn.CPoolProxy.sendRequestEntity(CPoolProxy.java:162)
        at com.github.dockerjava.shaded.org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:238)
        at com.github.dockerjava.shaded.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at com.github.dockerjava.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        ... 20 more
Caused by: org.newsclub.net.unix.AFUNIXSocketException: Broken pipe
        at org.newsclub.net.unix.NativeUnixSocket.write(Native Method)
        at org.newsclub.net.unix.AFUNIXSocketImpl$AFUNIXOutputStream.write(AFUNIXSocketImpl.java:251)
        ... 50 more

> Task :createAppImage FAILED
Building image using context '/Users/dpancholi/dev/sampleproj'.
Using Dockerfile '/Users/dpancholi/dev/sampleproj/Dockerfile'
Using tag 'myTag' for image.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createAppImage'.
> com.github.dockerjava.shaded.org.apache.http.client.ClientProtocolException
```

**Comment by cdancy** [comment] 2018-05-29 20:56
@dpancs no problem but I'm going to re-open this ISSUE as I think you may have stumbled upon a bug but I'll need more time to confirm.

**Comment by marcoebbinghaus** [comment] 2018-06-13 14:27
I have the same problem 

> Could not find com.aries:docker-java-shaded:3.0.14

. Even though I added jcenter() in the repositories-section. It is working when adding 
`repositories {
         jcenter()
 } `

explicitly into my DockerBuildImage-Task.

**Comment by cdancy** [comment] 2018-06-13 14:55
Thanks for reporting @marcoebbinghaus. It seems to be an issue with how we attempt to resolve that library at runtime. We basically check if there are any repos defined on the buildscript block, and if not, fallback to the repository block. May have to do some extra checking/validation here for sub-projects.

**Comment by cdancy** [comment] 2018-07-03 15:15
Fix for this ... quirk ... should be in latest build if folks want to give things a go.

**Closed** 2018-07-03 15:15 UTC
Labels: question

**Comment by priitliivak** [comment] 2018-07-16 11:07
Still managed to replicate this with 3.4.4 release

**Comment by cdancy** [comment] 2018-07-16 11:50
@priitliivak if that's the case you may have multiple versions of cglib on your path which are NOT coming from this library. If you can put together a reproducible sample project I can take a look but we're now using a shaded version of cglib which has a package path that is known only to the library itself so nothing else would be picking it up.

**Comment by unlimitedsola** [comment] 2018-08-28 23:42
@cdancy I can't understand why do we have to add `jcenter()` into the root `repositories` block instead of the one inside the `buildscript`?

**Comment by cdancy** [comment] 2018-08-31 14:10
@unlimitedsola is your question related to this issue/version or more in general?
