### ISSUE TITLE
NoClassDefFoundError: javax/activation/DataSource

### ISSUE THREAD

**Issue by segator** [bmuschko/gradle-docker-plugin#765] opened 2019-03-11 08:06 UTC
I can reproduce this error with openJDK 11 and gradle-docker-plugin 4.2.6 version
 ```groovy
task buildDockerImage(type: com.bmuschko.gradle.docker.tasks.image.DockerBuildImage) {
    inputDir = file(project.buildDir)
    buildArgs = ["JAR_FILE":"jar.archivePath.name"]
    dockerFile = file("./src/main/docker/Dockerfile")
    tags = ["global-library/gradle-test:${project.version}"]
}
```

This is the error
```
java.lang.NoClassDefFoundError: javax/activation/DataSource
        at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3138)
        at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2358)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1378)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.Utilities$3.run(Utilities.java:1374)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1374)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1317)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:83)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:148)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:180)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:180)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:740)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:694)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:337)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:175)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:238)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 49 more
MultiException stack 2 of 2
java.lang.IllegalArgumentException: Errors were discovered while reifying SystemDescriptor(
        implementation=com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.DataSourceProvider
        contracts={com.bmuschko.gradle.docker.shaded.javax.ws.rs.ext.MessageBodyWriter,com.bmuschko.gradle.docker.shaded.javax.ws.rs.ext.MessageBodyReader}
        scope=com.bmuschko.gradle.docker.shaded.javax.inject.Singleton
        qualifiers={}
        descriptorType=CLASS
        descriptorVisibility=NORMAL
        metadata=
        rank=0
        loader=null
        proxiable=null
        proxyForSameScope=null
        analysisName=null
        id=14
        locatorId=0
        identityHashCode=1000826319
        reified=false)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:705)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:464)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2310)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.access$1200(ServiceLocatorImpl.java:128)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1395)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1390)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.hk2.utilities.cache.internal.WeakCARCacheImpl.compute(WeakCARCacheImpl.java:128)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1452)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1377)
        at com.bmuschko.gradle.docker.shaded.org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1366)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.getAllServiceHolders(AbstractHk2InjectionManager.java:158)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.getAllServiceHolders(ImmediateHk2InjectionManager.java:54)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.inject.Providers.getServiceHolders(Providers.java:337)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:175)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory.initialize(MessageBodyFactory.java:238)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.MessageBodyFactory$MessageBodyWorkersConfigurator.postInit(MessageBodyFactory.java:136)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig$State.lambda$initRuntime$2(ClientConfig.java:470)
        at java.base/java.util.Arrays$ArrayList.forEach(Arrays.java:4390)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:470)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
        at com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
        at com.github.dockerjava.jaxrs.async.POSTCallbackNotifier.response(POSTCallbackNotifier.java:29)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:50)
        at com.github.dockerjava.jaxrs.async.AbstractCallbackNotifier.call(AbstractCallbackNotifier.java:24)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)


The following warnings have been detected: WARNING: HK2 failure has been detected in a code that does not run in an active Jersey Error scope.
WARNING: HK2 service reification failed for [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.message.internal.DataSourceProvider] with an exception
```
```

**Comment by bmuschko** [comment] 2019-03-11 14:23
Can you please create a minimal sample project on GitHub that reproduces the issue (including a checked-in Wrapper)? I can't make it happen with the information you provided.

**Comment by bmuschko** [comment] 2019-03-15 21:53
@segator Did this issue clear up for you? I can't reproduce it as mentioned before. I will likely close the issue soon if I don't hear back from you.

**Comment by bmuschko** [comment] 2019-03-22 12:54
I am closing this issue as I can't reproduce it and haven't heard back.

**Closed by bmuschko** 2019-03-22 12:54 UTC
Labels: question
