### ISSUE TITLE
platform, buildArgs not passed or affecting docker for some reason

### ISSUE THREAD

**Issue by doctorpangloss** [bmuschko/gradle-docker-plugin#1055] opened 2022-02-21 00:46 UTC
### Expected Behavior
If I set a `buildArg` called `ARCH` in my task, it does not appear to affect the build.

### Current Behavior
The build acts like it didn't receive the `ARCH` build arg. It also seems to ignore platform (???).

### Context
My dockerfile looks like this:

```
ARG ARCH
FROM --platform=$ARCH ghcr.io/zcube/bitnami-compat/keycloak:16.1.1
...
RUN touch /$ARCH.txt
```
and it fails with
```
touch: cannot touch '/.txt': Permission denied
```
i.e., it ignores the build arg.

My task looks like
```
...
                def createImageTask = project.tasks.register("xxx", DockerBuildImage) {
                  group = 'docker'
                  noCache.set(true)
                  inputDir.set(project.file(dockerFileFile.parent))
                  dockerFile.set(dockerFileFile)
                  buildArgs['ARCH'] = dockerPlatform
                  platform.set("linux/arm64")
                }
                
```

Weirdly, `noCache` is ignored. Debugging, the command clearly contains these args.
<img width="1593" alt="Screen Shot 2022-02-20 at 4 45 09 PM" src="https://user-images.githubusercontent.com/2229300/154872365-f57ef33e-a26d-4811-95db-ed91f6a5133a.png">

Console:
```
Building image using context '/xxx'.
Using Dockerfile '/xxx/Dockerfile'
Using images 'xxx/x:latest', 'xxx:arm64-latest'.
Step 1/6 : ARG ARCH
Step 2/6 : FROM --platform=$ARCH ghcr.io/zcube/bitnami-compat/keycloak:16.1.1
 ---> 97eda9f6022f
Step 3/6 : COPY profile.properties /opt/bitnami/keycloak/standalone/configuration/profile.properties
 ---> cdb4de260031
Step 4/6 : COPY xxx-keycloak-theme.jar /opt/bitnami/keycloak/standalone/deployments
 ---> 9c3c1277c3f7
Step 5/6 : RUN touch /$ARCH.txt
 ---> Running in 81bc39d63f69
touch: cannot touch '/.txt': Permission denied
```

### Your Environment
macOS Apple Silicon
Latest versions of the docker plugin, the docker-java API, Java 17, Gradle 7.2

**Comment by bmuschko** [comment] 2022-02-23 00:58
It's not really what I am seeing. Please have a look at this test case: https://github.com/bmuschko/gradle-docker-plugin/commit/44fc034f24cba99760ca4b46f44cfde3a3e640a3. The general mechanism seems to be working fine. Maybe you have to use curly braces for a variable that follows with a dot? Did you check that `dockerPlatform` actually has a value?

**Comment by appmana-accounts** [comment] 2022-02-23 04:57
I'll start working on a reproduction.

**Comment by bmuschko** [comment] 2022-03-02 23:38
I am closing this issue for now as I haven't heard back from you.

**Comment by The-Neo-Noir** [comment] 2022-05-05 20:30
I can confirm this issue exists.


```
ARG TARGETPLATFORM
RUN echo '===========================SETTING UP FOR '$TARGETPLATFORM'=========================='
```

I am using both the platform and buildArgs but the TARGETPLATFORM never prints 
```
task()...{
 buildArgs['TARGETPLATFORM'] = 'linux/arm64'
 platform.set("linux/arm64")
}
```

But If I run my docker file as  % docker build --build-arg TARGETPLATFORM=linux/arm  -t abc .

Then it prints the way I expect it to be.
Note that the developer may be using this args to do conditional tasks , for example in my case I check for the platform and take platform specific actions. 
Please open this ticket

**Comment by bmuschko** [comment] 2022-05-24 01:06
Happy to reopen but please provide a functional test case as a pull request that reproduces the issue.

**Comment by bmuschko** [comment] 2022-10-16 01:45
Closing again as the issue didn't get any traction from the community.

**Closed by bmuschko** 2022-10-16 01:45 UTC
Labels: question

**Comment by krystian-panek-wttech** [comment] 2023-03-09 17:14
I am using your task:

```
tasks {
    val buildImage = register<DockerBuildImage>("image") {
        /// ...
        platform.set("linux/amd64")
    }
}

```

however, it does not have the same effect as running `docker build --platform=linux/amd64`
Do I miss sth or it just does not work?

I checked `uname -m` while building image and if that `platform.set()` call is set then I have still aarch64 from my host machine instead of desired x86_64 like when calling `docker build` natively without Gradle... :/

**Comment by bmuschko** [comment] 2023-03-09 18:53
@krystian-panek-wttech This needs to figured out with the Docker Java library. I am pretty sure it's an issue there. Keep in mind that the plugin does not use the `docker` executable. Thus, the behavior could be different. Any chance you can submit a PR with a functional test that demonstrates the current behavior?

**Comment by krystian-panek-wttech** [comment] 2023-03-10 07:34
unfortunately, I have no time for this at all :( I will use just native docker commands instead. But at least I wanted to confirm similar doubts that sth is wrong here.

**Comment by krystian-panek-wttech** [comment] 2023-04-21 06:50
good to know, thanks; but wiping out images before still looks cumbersome ;)

**Comment by bmuschko** [comment] 2023-04-21 13:40
@krystian-panek-wttech That doesn't necessarily mean that you need to do so. I was just talking about my setup. Depending on the Docker daemon your are using, you may have to make sure that certain features are enabled.
