### ISSUE TITLE
How to access Azure Container Registry

### ISSUE THREAD

**Issue by tranpeter** [bmuschko/gradle-docker-plugin#843] opened 2019-07-30 16:54 UTC
I'm trying to build a very simple image from a base image located in [Azure Container Registry (ACR)](https://azure.microsoft.com/en-us/services/container-registry/).

When I create my Dockerfile and specify the base image from the public Docker Hub, it works perfectly. For example:

`

    task createDockerfile(type: Dockerfile) {
        from 'ubuntu:12.04'
        label(['maintainer': 'Peter Tran "ptran@pros.com"'])
    }

`

However when I modify

`

    task createDockerfile(type: Dockerfile) {
        from 'prosprod.azurecr.io/alpine/common-base:latest'
        label(['maintainer': 'Peter Tran "ptran@pros.com"'])
    }

`

### Expected Behavior
I would expect this to work since I can go to the command-line and just type: docker build . and it builds correctly.

### Current Behavior
When I execute ./gradlew buildImage --info I get the following.

> Task :buildImage FAILED
The following hints have been detected: HINT: Cannot create new registration for component type class com.bmuschko.gradle.docker.shaded.com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider: Existing previous registration found for the type.

Selected ExecutorServiceProvider implementation [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.DefaultClientAsyncExecutorProvider] to be used for injection of executor qualified by [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientAsyncExecutor] annotation.
Selected ScheduledExecutorServiceProvider implementation [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.DefaultClientBackgroundSchedulerProvider] to be used for injection of scheduler qualified by [com.bmuschko.gradle.docker.shaded.org.glassfish.jersey.client.ClientBackgroundScheduler] annotation.
Task ':buildImage' is not up-to-date because:
  Task.upToDateWhen is false.
Building image using context '/Users/ptran/work/gradle-docker-plugin/build/docker'.
Using tags 'ptran/myimage:latest' for image.

However, if I manually pull down the image (prosprod.azurecr.io/alpine/common-base:latest) first and it's already cached, then the Gradle buildImage task works.

### Your Environment
- Mac OSX
- Docker Desktop version 2.0.0.3

**Comment by orzeh** [comment] 2019-07-30 21:09
@tranpeter did you provide valid credentials to access ACR? Remember that this plugin doesn't automatically read your `~/.docker/config.json` (see #743).

**Comment by tranpeter** [comment] 2019-07-30 21:37
Yes. I've logged into our ACR. You can see the steps below. If I wasn't logged into ACR, I would have not been able to execute "docker build ." However, if I execute this via the Gradle task it does not.


   ptran docker $ az account set -s <SUBSCRIPTION>
   ptran docker $ az acr login --name <ACR>
   Login Succeeded
   ptran docker $
   ptran docker $
   ptran docker $ more Dockerfile
   FROM prosprod.azurecr.io/alpine/common-base:latest
   LABEL maintainer="Peter Tran \"ptran@pros.com\""
   ptran docker $
   ptran docker $
   ptran docker $ docker build .
   Sending build context to Docker daemon  2.048kB
   Step 1/2 : FROM prosprod.azurecr.io/alpine/common-base:latest
   latest: Pulling from alpine/common-base
   ee903f833e63: Pull complete
   25bce526d050: Pull complete
   Digest: sha256:6dce7851fcf09b3bf9a62b629e8c662867a12045388dbb594a516edb48f1c5fb
   Status: Downloaded newer image for prosprod.azurecr.io/alpine/common-base:latest
    ---> 4b74e478f9a8
   Step 2/2 : LABEL maintainer="Peter Tran \"ptran@pros.com\""
    ---> Running in 508d8340fabb
   Removing intermediate container 508d8340fabb
    ---> 198f5c8c6e65
   Successfully built 198f5c8c6e65

**Comment by orzeh** [comment] 2019-07-30 21:41
@tranpeter OK, but you didn't provide credentials in build script. Please refer to our [User Guide](https://bmuschko.github.io/gradle-docker-plugin/#working_with_a_tls_enabled_docker_instance) for more details and examples.

**Comment by tranpeter** [comment] 2019-07-30 21:53
That's the gist though...

I don't need to provide the credentials on the command-line. I'm already logged into Azure via the command-line interface (Azure CLI). I hacked around Azure Container Registry and there is an option to enable the Admin account to allow me to pass in the admin username and password, but this goes against our security process which is we're not allowed to store clear text passwords.

Once I log into ACR it persists my credentials auto-magically.

Here is my ~/.docker/config.json.

ptran docker $ more ~/.docker/config.json
{
        "auths": {
                "gsotest.azurecr.io": {},
                "prosdev.azurecr.io": {},
                "prosprod.azurecr.io": {}
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/18.09.2 (darwin)"
        },
        "credsStore": "osxkeychain",
        "stackOrchestrator": "swarm"
}

If I can execute docker build on the command-line, should I be able to execute the Gradle task to build the image?

Thanks for all the prompt reply!

**Comment by tranpeter** [comment] 2019-07-30 21:54
Oh wait...I reread your comment above 

> Remember that this plugin doesn't automatically read your ~/.docker/config.json

So how do I get the plugin to read my config.json?

**Comment by tranpeter** [comment] 2019-07-30 22:13
Setting DOCKER_CONFIG did not help.

**Comment by bmuschko** [comment] 2019-09-28 22:00
> So how do I get the plugin to read my config.json?

You don't at the moment. We are waiting for community contributions for this feature. Please see https://github.com/bmuschko/gradle-docker-plugin/issues/746 and https://github.com/bmuschko/gradle-docker-plugin/issues/743 for more information.

**Comment by kgrech** [comment] 2019-09-29 06:33
I had the same issue. Setting ``DOCKER_CONFIG`` does not help.
I have solved with Exec type, which does not use the plugin and docker-java:
```
task dockerpush(type: Exec, dependsOn: dockerfile) {
    commandLine = ['docker', 'push', "$dockerRepoUrl/${project.name}:$version"]
}
```

**Comment by bmuschko** [comment] 2019-10-02 01:50
> I had the same issue. Setting DOCKER_CONFIG does not help.

As it is not supported by this plugin right now. That's what I eluted to in my previous comment.

**Comment by kgrech** [comment] 2019-10-02 15:39
@bmuschko I've made a step forward to the solution of this in the [PR#865](https://github.com/bmuschko/gradle-docker-plugin/pull/865).

The PR fixes only pull and push the case. The challenge in case of docker build command is that we need to get the image name form the ``FROM`` statement of the docker file and then we can apply the same ``RegistryAuthLocator`` for build task the same way as for pull and push.

The problem is that I am not able to find the API to get the ``from`` image. Any ideas?

**Comment by bmuschko** [comment] 2019-10-06 14:52
@kgrech Thanks for providing the PR. I am going to have a look soon.

**Comment by bmuschko** [comment] 2019-10-18 01:59
@tranpeter For the time being you will likely have to provide the credentials via the `DockerExtension` as [described in the user guide](https://bmuschko.github.io/gradle-docker-plugin/#extension). I am going to close the issue for now.

**Closed by bmuschko** 2019-10-18 01:59 UTC
Labels: question
