### ISSUE TITLE
Login to Amazon ECR not working

### ISSUE THREAD

**Issue by dpr-rec** [bmuschko/gradle-docker-plugin#216] opened 2016-06-02 13:35 UTC
Hi,

I'm trying to build a container on a local docker installation. The Dockerfile references a parent image that is published to Amazon's ECR docker registry. The login to the AWS registry is somewhat "different"
1. One needs an AWS user with an AWS API access key
2. With this access key and the corresponding secret one can get the docker login command for the ECR registry:

```
$ aws ecr get-login --region us-east-1
docker login -u AWS -p NsdfnSd....  -e none https://<aws-account-id>.dkr.ecr.us-east-1.amazonaws.com
```

The password is very long (almost 1100 characters in total) and is made up of `[A-Za-z/+]` characters.

If I use the generated login command in docker itself it works (Docker 1.11.0), but if I try to provide the credentials inside the `registryCredentials` closure, I can't built my image

``` groovy
registryCredentials {
    url = 'https://<aws-account.id>.dkr.ecr.us-east-1.amazonaws.com'
    username = 'AWS'
    password = 'NsdfnSd...'
    email = 'none'
}
```

The built always fails with a `DockerClientException`:

```
Caused by: com.github.dockerjava.api.DockerClientException: Could not build image: unauthorized: authentication required
        at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:71)
        at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:48)
        ... 36 more
```

**Comment by double16** [comment] 2016-06-02 14:49
I am able to use ECR to pull/push images with this plugin. I don't specify the email, try removing that. Also, the token expires after 24 hours, is your token expired?

**Comment by dpr-rec** [comment] 2016-06-02 16:55
Thanks for the info.

I acquired the token just minutes before starting the build. And as mentioned login from within the docker shell with the generated login command...

What does your docker `FROM` statement look like? Mine looks like this:

```
FROM <aws-account.id>.dkr.ecr.us-east-1.amazonaws.com/repository/java:java8
...
```

**Comment by double16** [comment] 2016-06-02 18:12
I'm building it dynamically based on environment vars so I can support local and AWS, but it looks something like:
```
FROM <aws-account.id>.dkr.ecr.us-east-1.amazonaws.com/project_base_image:latest
```

Did you publish your own 'java' repository? It looks a lot like the naming for Docker Hub's java.

**Comment by dpr-rec** [comment] 2016-06-03 08:01
Yes, the repositories name in ECR is `repository/java`

Is there some way (other than gradle's `--debug`) switch to enable some debug logging for this plugin or the Java Docker API to see what actually happens, what requests are send and what responses are received?

**Comment by bemnum** [comment] 2016-06-20 06:40
Hello,

The same problem exists, when using Nexus Repository Manager 3.0.0-03:
`Caused by: com.github.dockerjava.api.DockerClientException: Could not build image: unauthorized: authentication required`

Gradle-docker cannot pull image from registry which requires authentication.

The problem does not exists if I use docker login <...> and docker pull <...> from command line.

My example docker has only one line:
`$ cat mydocker-prod/Dockerfile
FROM docker-registry.net.example/mydockerpr/mydocker`

In build.gradle there is a proper registryCredentials section and task "mydocker-prod_buildDocker"(type: DockerBuildImage). 

Regards,
BN

**Comment by cdancy** [comment] 2016-07-05 14:41
@dpr-rec you could use wire-shark to see what exactly is going out OR build a [docker-java](https://github.com/docker-java/docker-java) client yourself (which is what we do behind the scenes anyway) and add the [necessary logback](https://github.com/docker-java/docker-java/issues/544) file to your classpath to capture the wire logs.

**Comment by nyounger** [comment] 2016-07-07 16:48
I believe I have ran into the same issue as the above.  My grade build file docker section looks like: 
`
docker {
    registryCredentials {
        url = 'https://registry.privateregistry.int/'
        username = 'privateregistryuser'
        password = 'privateregistrypassword'
        email = 'email@email.com'
    }
}
`
When I use wireshark to look at the packet exchange I see its trying to authenticate with auth.docker.io instead of the private registry.  When looking at AbstractDockerRemoteApiTaskFunctionalTest.groovy with test "Can create and execute custom remote API task with extension values" it appears that when setting a custom value for the auth url it is still expecting docker.io as the url.  

`         
   docker {
                url = 'tcp://remote.docker.com:2375'
                certPath = new File('${customCertPath.canonicalPath}')
                registryCredentials {
                    url = 'https://some.registryCredentials.com/'
                    username = 'johnny'
                    password = 'pwd'
                    email = 'john.doe@gmail.com'
                }
            }
            task customDocker(type: CustomDocker)
            import com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask
            class CustomDocker extends AbstractDockerRemoteApiTask {
                @Override
                void runRemoteCommand(dockerClient) {
                    assert dockerClient
                    assert dockerClient.dockerClientConfig.dockerHost == new URI('tcp://remote.docker.com:2375')
                    assert dockerClient.dockerClientConfig.dockerConfig == "${System.properties['user.home']}/.docker"
                    assert dockerClient.dockerClientConfig.registryUrl == 'https://index.docker.io/v1/'
                    assert dockerClient.dockerClientConfig.registryUsername == '${username}'
                    assert !dockerClient.dockerClientConfig.registryPassword
                    assert !dockerClient.dockerClientConfig.registryEmail
                }
            }
`
I believe it should be:
`
            docker {
                url = 'tcp://remote.docker.com:2375'
                certPath = new File('${customCertPath.canonicalPath}')

                registryCredentials {
                    url = 'https://some.registryCredentials.com/'
                    username = 'johnny'
                    password = 'pwd'
                    email = 'john.doe@gmail.com'
                }
            }

            task customDocker(type: CustomDocker)

            import com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask

            class CustomDocker extends AbstractDockerRemoteApiTask {
                @Override
                void runRemoteCommand(dockerClient) {
                    assert dockerClient
                    assert dockerClient.dockerClientConfig.dockerHost == new URI('tcp://remote.docker.com:2375')
                    assert dockerClient.dockerClientConfig.dockerConfig == "${System.properties['user.home']}/.docker"
                    assert dockerClient.dockerClientConfig.registryUrl == 'https://some.registryCredentials.com/'
                    assert dockerClient.dockerClientConfig.registryUsername == 'johnny'
                    assert !dockerClient.dockerClientConfig.registryPassword == 'pwd'
                    assert !dockerClient.dockerClientConfig.registryEmail == 'john.doe@gmail.com'
                }
            }
`
I could be wrong on this however.  I am fairly new to Groovy and Docker in general.

Best 

-Nate

**Comment by borntorock** [comment] 2016-11-04 09:53
@double16 Hi, As you informed that "I am able to use ECR to pull/push images with this plugin. " Can you Please help us know how to authenticate with the ECR repository using this plugin. 

The token generated with the aws ecr command gets expired after every 12 hours.

**Comment by dpr-rec** [comment] 2016-11-04 10:45
@cdancy are you still interested in my wireshark results? I think from the output in @nyounger's comment it's pretty obvious what is going wrong?!

**Comment by double16** [comment] 2016-11-04 11:11
I built code to take AWS credentials and create the token in Gradle. Unfortunately it's in a private repo right now but I started a plugin to do just this. Let me see if I can at least get it extracted in the next day or so.

**Comment by borntorock** [comment] 2016-11-07 05:30
@double16 Did you got a chance to extract the code that you have built for taking AWS credentials and creating the token in Gradle. Can you Please update.

**Comment by double16** [comment] 2016-11-07 13:44
Take a look at https://bitbucket.org/double16/gradle-aws-ecr-plugin

It's pre-alpha as a plugin, but the important code works in my other project. Please create issues, PR, whatever. I'll be finishing this up in the near future.

**Comment by cdancy** [comment] 2016-12-13 11:52
Closing issue for now. @dpr-rec feel free to re-open if needed or use @double16 version of our plugin which may make things easier for you when working with AWS.

**Closed by cdancy** 2016-12-13 11:52 UTC
