### ISSUE TITLE
Cohabitation with other plugins

### ISSUE THREAD

**Issue by Olivier-l** [bmuschko/gradle-docker-plugin#244] opened 2016-07-15 11:06 UTC
Hello, we began to use this plugin in our project and we find it very useful. 
When we define the tasks for the plugin in the main build.gradle file everything works ok.

However when we try  to organize gradle build logic in multiple files and we have several other plugins installed, it will throw the following exception :

11:47:46.757 [ERROR] [org.gradle.BuildExceptionReporter] 
11:47:46.757 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:47:46.757 [ERROR] [org.gradle.BuildExceptionReporter] 
11:47:46.758 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
11:47:46.758 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':buildMyAppImage'.
11:47:46.758 [ERROR] [org.gradle.BuildExceptionReporter] > Cannot invoke method withClasspath() on null object
11:47:46.758 [ERROR] [org.gradle.BuildExceptionReporter] 
11:47:46.773 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
11:47:46.774 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildMyAppImage'.
11:47:46.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
11:47:46.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
11:47:46.774 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:208)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:186)
11:47:46.775 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:111)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
11:47:46.776 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.Factories$1.create(Factories.java:22)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:47)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLauncher.java:189)
11:47:46.777 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:171)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:35)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:104)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:97)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleLauncher.java:184)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:97)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:93)
11:47:46.778 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:27)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:72)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:44)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:49)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:47:46.779 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
11:47:46.780 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.util.Swapper.swap(Swapper.java:38)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:47:46.781 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
11:47:46.782 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException: Cannot invoke method withClasspath() on null object
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask$runInDockerClassPath.callCurrent(Unknown Source)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.start(AbstractDockerRemoteApiTask.groovy:56)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
11:47:46.783 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 	... 69 more
11:47:46.784 [ERROR] [org.gradle.BuildExceptionReporter] 
11:47:46.784 [LIFECYCLE] [org.gradle.BuildResultLogger] 
11:47:46.784 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED

Thanks

**Comment by orzeh** [comment] 2016-07-15 11:11
It would be easier to help you if you could provide build script or example project that reproduces the issue.

You may also look at #228

**Comment by cdancy** [comment] 2016-07-19 13:19
@Olivier-l is this still an issue? As @orzeh said: it would be much easier to help and diagnose the issue if we had an example of what you're trying to do.

**Comment by Olivier-l** [comment] 2016-07-20 13:12
Hi,
Thanks for your answers, there is still an issue.
To workaround this problem, we are now including the docker inside the build.gradle
It's less clear, but it works.

Thanks

**Comment by christianwnk** [comment] 2016-07-20 14:51
Hi, I´m getting the same Exception with the identical stacktrace "Cannot invoke method withClasspath() on null object".

The beginning of my build.gradle:
`buildscript {
    repositories {
        jcenter()
		mavenCentral()
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.0.0'
    }	
}

plugins {
  id 'org.hidetake.ssh' version '1.6.0'
  id "de.undercouch.download" version "3.1.0"
}

apply plugin: 'java'
apply plugin: 'findbugs'
apply plugin: 'eclipse'
apply plugin: 'maven-publish'


apply from: 'gradle/parameters.gradle'
apply from: 'gradle/docker.gradle'

import de.undercouch.gradle.tasks.download.Download

configurations.all {
    resolutionStrategy {
        cacheDynamicVersionsFor 0, "seconds"
        cacheChangingModulesFor 0, "seconds"
    }
}

sourceSets {
	 integrationTest {
        java {
            srcDir 'src/integrationtest/java'
        }
        resources {
            srcDir 'src/integrationtest/resources'
        }
        compileClasspath += sourceSets.main.runtimeClasspath
    }
}

sourceCompatibility = '1.8'

subprojects {
    eclipse.project {
        name = "${rootProject.name}-${project.name}"
    }
}`

My docker.gradle (Please note if have replaced some private information with examples (repository names etc)):

`//DOCKER SETTINGS / TASKS 

buildscript {
    repositories {
        jcenter()
		mavenCentral()
    }
	
	dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.0.0'
    }	
}

apply plugin: 'com.bmuschko.docker-remote-api'

import com.bmuschko.gradle.docker.tasks.container.*
import com.bmuschko.gradle.docker.tasks.image.*

def containerId = 'testcontainer'
def repositoryName = 'my.private.registry.com:5000/myuser/integrationtest'
def imageTag = 'latest'

docker {
	url = parameters[DOCKER_HOST]
	certPath = new File(System.properties['user.dir'], 'docker/certs/my.private.registry.com')
	
	registryCredentials {
        url = 'https://my.private.registry.com:5000'
        username = 'jenkins'
        password = 'jenkins'
        email = 'user@test.com'
    }
}

task listImages(type: DockerListImages) {
	showAll true
}

task pullImage(type: DockerPullImage) {
	repository = repositoryName;
	tag = 'latest';

	doLast {
		println 'Image ' + repositoryName + ':' + tag + ' pulled from registry'
	}
}

task createContainer(type: DockerCreateContainer) {
	doFirst {
		println 'Creating container with name ' + containerId + ' from image ' + repositoryName + ':' + imageTag
	}

	targetImageId { repositoryName + ':latest' }
	containerName = containerId;
	
	portBindings = ['8080:8080', '8022:22']
	
	env = ['TZ=Europe/Berlin']
	
	doLast {
		println 'Container created'
	}
}
`

It seems that the ThreadContextClassLoader in AbstractDockerRemoteApiTask.groovy (line 62) is null.

Thanks for your help!

**Comment by orzeh** [comment] 2016-07-20 22:11
@Olivier-l @christianwnk please see [my comment here](https://github.com/bmuschko/gradle-docker-plugin/issues/248#issuecomment-234098958).

**Comment by christianwnk** [comment] 2016-07-21 10:58
I have solved the issue with your help and the comments from #248. Things I have done:

I have removed the
 ````groovy
plugins {
  id 'org.hidetake.ssh' version '1.6.0'
  id "de.undercouch.download" version "3.1.0"
}
 ````

from my build.gradle and instead I added the the entries to the classpath in the buildscript{} on build.gradle and docker.gradle. My buildscript now looks like: 

````groovy
buildscript {
    repositories {
        jcenter()
		mavenCentral()
		
		maven {
			url "https://plugins.gradle.org/m2/"
		}
    }

    dependencies {
        classpath 'com.bmuschko:gradle-docker-plugin:3.0.0'
		classpath 'org.hidetake:gradle-ssh-plugin:2.4.0'
		classpath 'de.undercouch:gradle-download-task:3.1.0'
    }	
}
````

Last I applied the plugins: 
````groovy
apply plugin: "org.hidetake.ssh"
apply plugin: 'de.undercouch.download'
````

Now i can run the docker tasks without problems.

**Comment by orzeh** [comment] 2016-07-21 11:25
I'm happy it works for you.
However we should track down the cause of this issue.
I'm closing this and if you are interested please follow #248

**Closed by orzeh** 2016-07-21 11:25 UTC
Labels: question

**Comment by fhanik** [comment] 2017-08-09 17:58
we fixed our build by

replacing 

    apply plugin: 'com.bmuschko.docker-remote-api'
with

    apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin

per documentation at https://github.com/bmuschko/gradle-docker-plugin

and that solved the issue of 

     Cannot invoke method withClasspath() on null object    
    "at com.bmuschko.gradle.docker.tasks.AbstractDockerRemoteApiTask.runInDockerClassPath(AbstractDockerRemoteApiTask.groovy:62)"
