### ISSUE TITLE
Docker Java dependency clashes with Testcontainers

### ISSUE THREAD

**Issue by frankkoornstra** [bmuschko/gradle-docker-plugin#954] opened 2020-07-22 15:08 UTC
When I combine this plugin with [Testcontainers](https://www.testcontainers.org/) to test the built image, Testcontainers runs into an NPE because of deserialization issues. Testcontainer's author has [tracked it down to](https://testcontainers.slack.com/archives/C1SUBPZK6/p1595329713276000?thread_ts=1595256124.253800&cid=C1SUBPZK6) the following:
>it looks like gradle-docker-plugin “embeds” docker-java, both api and core, and then shades Jackson [...] you should report to them because it breaks any project that uses docker-java

### Expected Behavior
Be able to combine this plugin with any other plugin that relies on Docker Java and Jackson

### Current Behavior
Deserialization starts to fail. I've created a [reproducer](https://github.com/frankkoornstra/testcontainers-reproducer) that shows the issue.

### Context
(none)

### Steps to Reproduce (for bugs)
Take a look at the [reproducer](https://github.com/frankkoornstra/testcontainers-reproducer)

### Your Environment
Ran the reproducer on several systems, all with the same result

**Comment by bmuschko** [comment] 2020-07-24 13:54
Thanks for reporting. Are you interested in sending a pull request?

**Comment by frankkoornstra** [comment] 2020-07-27 09:09
To be honest: I don't have that much experience yet with the dependency system in the JVM world yet so I don't know if I can fix it. I can only understand the suggestions that were given in the Slack chat partly and was already happy that I can show what was wrong :D

**Comment by bmuschko** [comment] 2020-07-29 00:35
@frankkoornstra Why do you define the plugin as a dependency for the project source code and not for the build script? Can you explain what you are trying to achieve? Are you trying to build a Gradle plugin and then reference a class of the plugin from your plugin code? https://github.com/frankkoornstra/testcontainers-reproducer/blob/master/build.gradle.kts#L14

**Comment by frankkoornstra** [comment] 2020-07-29 11:53
I'm building a Gradle plugin (let's call it `pA`) and in there applying your plugin (`pB`) to the project that `pA` is applied to. That way `pA` can define new tasks based on `pB` tasks in the project `pA` is applied to.

This might be a bit of an edge case and I already found another solution: simply using the Docker client because it was less hassle than I thought it would be.

**Comment by bmuschko** [comment] 2020-07-29 13:06
Got it. I am going to close this for now. Reason: Typically you add the plugin to the buildscript's classpath. At this time, Gradle does not create its own classloader per plugin and can lead to issues when you have multiple versions of the same dependency. That's really the only reason why the plugin's dependencies are shaded. I might look at this again in case other people complain.

**Comment by twarner-sofi** [comment] 2022-09-08 23:09
We are trying to use com.bmuschko:gradle-docker-plugin:7.4.0 and org.testcontainers:postgresql:1.17.3 in a plugin we are building. Because of how gradle-docker-plugin includes docker-java classes in its own jar without any shading, I think its classes are conflicting with those of the docker-java dep brought in by testcontainers and causing errors.

I think if you are going to include the docker-java classes, they should be shaded in their own package name.

**Comment by bmuschko** [comment] 2022-09-09 02:07
@twarner-sofi Looks like the shading broke at some point. The Docker Java package should be shaded: https://github.com/bmuschko/gradle-docker-plugin/blob/master/build.gradle.kts#L27.

**Comment by Sineaggi** [comment] 2022-09-09 18:58
Would it be possible to not shade the dependencies instead?

**Comment by bmuschko** [comment] 2022-09-11 23:17
@Sineaggi It's currently not shaded apparently.

**Comment by Sineaggi** [comment] 2022-09-12 17:01
I mean would it be possible to completely disable shading of all dependencies instead.

**Comment by bmuschko** [comment] 2022-09-28 14:13
@Sineaggi Those dependencies need to be shaded as Gradle doesn't create separate classloaders per plugin. You may end up breaking another plugin that needs the same dependency but with a different version.

**Comment by Sineaggi** [comment] 2022-09-28 17:47
On the other hand, shadowing is currently breaking other plugins trying to use the same dependencies.

**Comment by bmuschko** [comment] 2022-10-16 00:22
@britter That was the intention [here](https://github.com/bmuschko/gradle-docker-plugin/blob/master/build.gradle.kts#L27-L29). I guess this logic got broken with an upgrade of the shadow plugin or a Gradle upgrade. Would you have time to look into this?

**Comment by britter** [comment] 2022-11-09 16:04
@bmuschko I won't have time to look into this before the end of November but hope to have some more time in December 👍🏻

**Comment by meiblorn** [comment] 2022-11-17 03:37
It also doesn’t work with micronaut and https://github.com/revolut-engineering/jooq-plugin plugins

**Comment by bmuschko** [comment] 2022-12-19 23:14
@britter Do you have some time to look into this soon? I am planning to a release a new version soon and wanted to see if we can include a potential change for this issue.

**Comment by Sineaggi** [comment] 2022-12-19 23:29
@bmuschko I think the current issue is the docker java libraries aren't being relocated.

I've put together an mr https://github.com/bmuschko/gradle-docker-plugin/pull/1144

I do still think shading is causing more trouble than it's fixing.

**Comment by britter** [comment] 2022-12-20 07:59
@bmuschko sorry, I won't have time before Christmas and most likely not until end of January :(

**Closed** 2022-12-20 14:33 UTC
Labels: enhancement, docker-java
