### ISSUE TITLE
Repositories fallback plugin should not live in this plugin suite

### ISSUE THREAD

**Issue by bmuschko** [bmuschko/gradle-docker-plugin#794] opened 2019-04-23 02:28 UTC
### Expected Behavior

The plugin should be externalized and published separately. The functionality should be applied on-demand to avoid confusion. It is likely only useful functionality in two use cases:

1. A user (mostly beginners to Gradle) doesn't understand the difference in repository definitions.
2. A user understands the difference but doesn't want to repeat the repository definition.

### Current Behavior

Beginners to Gradle do not understand the difference between the list of repositories defined in the `buildscript` block and outside of the `buildscript` block. They serve different purposes. The functionality in `RepositoriesFallbackPlugin` was introduced to automatically use the same repositories. This could lead to confusion for users as the list of repositories is not ordered. With the latest versions of Gradle, user can also define that specific dependencies should be resolved from assigned repositories. Currently, the `RepositoriesFallbackPlugin` is applied by the `DockerRemoteApiPlugin`.

### Context

The functionality of [`RepositoriesFallbackPlugin`](https://github.com/bmuschko/gradle-docker-plugin/blob/master/src/main/groovy/com/bmuschko/gradle/docker/RepositoriesFallbackPlugin.groovy) is a cross-cutting concern. There's no point in defining it here. Other plugins have the same issue. This should really be configurable Gradle core functionality.

**Comment by cdancy** [comment] 2019-04-23 13:29
> With the latest versions of Gradle, user can also define that specific dependencies should be resolved from assigned repositories.

What would a solution look like then for end-users?

> Other plugins have the same issue. This should really be configurable Gradle core functionality.

But if gradle-core doesn't have a solution, and we can get around things with this hack of sorts, are we really going to put that back on our users?

**Comment by bmuschko** [comment] 2019-04-23 15:09
> What would a solution look like then for end-users?

It's described [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies).

And BTW repository order matters. Gradle will try to find dependencies top-down. Mixing in repositories with this plugin could have an impact on build performance if you define some other ones in `buildscript` already.

> But if gradle-core doesn't have a solution, and we can get around things with this hack of sorts, are we really going to put that back on our users?

Users will still have a solution. It would simply not live in this repository and published separately. Furthermore, the users need to be apply the plugin actively themselves.

```
apply plugin: 'com.bmuschko.docker-remote-api'
apply plugin: 'repositories.fallback'
```

In general it's just weird that the code is part of this plugin. I understand why we are doing it but it's a massive hack. You could have the exact same situation with any other plugin or even with plain Gradle core that defines dependencies in some form so it doesn't really belong here.

**Comment by cdancy** [comment] 2019-04-23 23:13
Wait a minute ... it may be this doesn't matter anymore now that we are declaring dependencies in a more proper way. This was initially done due to the way we were internally resolving the lib at runtime. Now that we are not doing that I think we may have simply outgrown the problem so to speak. Unless I'm mistaken...

**Comment by bmuschko** [comment] 2019-04-23 23:16
Good point. I kind of forgot that I changed it. ;-) Now, we have all transitive dependencies contained in the JAR as shaded packages. I'll delete the plugin. Wondering if it will break some people though as they won't have the magic behavior anymore.

**Closed** 2019-04-23 23:51 UTC
Labels: enhancement

**Comment by cdancy** [comment] 2019-04-24 13:52
> Wondering if it will break some people though as they won't have the magic behavior anymore.

It _may_ but things should just work "as intended" at least on our end. If ISSUE's come up then we can just say that's a gradle issue but if folks are relying on our previous hacks (which are not exactly made public) to make their greater build work than that is just shame on them :)
