### ISSUE TITLE
Extend the Spring Boot Dockerfile

### ISSUE THREAD

**Issue by AnakinPt** [bmuschko/gradle-docker-plugin#1213] opened 2024-02-15 16:01 UTC
I would like to extend the creationg of the Spring boot docker file to add volumes so I can have a volume in the image.

```
docker {
    springBootApplication {
        baseImage = 'amazoncorretto:21.0.2-alpine3.18'
        ports = [8081, 8080]
        images = ["myFantasticApp:${project.version.toString().replace('+', '_')}"]
    }
}
```
I would like to extend this image to add a volume in the image. I tried everything in the documentation, chapter 2.5 but nothing worked.

I'm using gradle 8.6

**Comment by bmuschko** [comment] 2024-02-19 00:32
Your question is basically a duplicate of https://github.com/bmuschko/gradle-docker-plugin/issues/1093. You can find my answer there. I have not gotten around to improving the API.

**Closed** 2024-05-08 00:56 UTC
Labels: duplicate, enhancement
